const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

const heroImg='https://images.unsplash.com/photo-1763485956292-6fb531f01b0c?auto=format&fit=crop&w=1800&q=85';
const diagImg='https://images.unsplash.com/photo-1543525469-65b61cc2bc06?auto=format&fit=crop&w=1400&q=85';
const images={
  Carrelage:'https://images.unsplash.com/photo-1782805153077-0e348cc5409d?auto=format&fit=crop&w=1400&q=85',
  Peinture:'https://images.unsplash.com/photo-1693985120993-e9b203ce7631?auto=format&fit=crop&w=1400&q=85',
  'Sol / parquet':'https://images.unsplash.com/photo-1743385199973-0f867a26c833?auto=format&fit=crop&w=1400&q=85',
  'Placo / isolation':'https://images.unsplash.com/photo-1768321902114-12b1777549a6?auto=format&fit=crop&w=1400&q=85'
};
const meta={
  Carrelage:['Carrelage','Préparation, calepinage, pose et joints.','▦'],
  Peinture:['Peinture','Préparer, protéger et appliquer dans le bon ordre.','◩'],
  'Sol / parquet':['Sol / parquet','Sous-couche, pose et finitions.','▥'],
  'Placo / isolation':['Placo / isolation','Rails, isolant, plaques et bandes.','▤']
};
const rooms=['Salle de bain','Cuisine','Salon / séjour','Chambre','Entrée / couloir','Terrasse','Autre'];
const levels=[['Débutant','Je découvre et je veux être très guidé.'],['Bricoleur','J’ai déjà réalisé quelques travaux.'],['Confirmé','Je suis autonome sur les bases.']];
const qualities=[['Éco','Priorité au budget'],['Standard','Bon équilibre qualité / prix'],['Premium','Priorité à la finition']];

const starter={id:1,title:'Salle de bain invités',category:'Carrelage',room:'Salle de bain',level:'Bricoleur',quality:'Standard',area:18,budget:890,steps:[['Protection et dépose',1],['Préparation des supports',1],['Étanchéité',0],['Calepinage et traçage',0],['Pose du carrelage',0],['Joints et finitions',0]],materials:[['Carrelage mural','19,8 m²',1],['Colle C2S1','4 sacs',0],['Joint hydrofuge','5 kg',0],['Croisillons autonivelants','270 pièces',1]]};
let projects=[];
try{projects=JSON.parse(localStorage.getItem('bricoach-projects')||'null')||[starter]}catch(e){projects=[starter]}
projects=projects.map(p=>({...p,room:p.room||'Pièce non précisée',level:p.level||'Débutant',quality:p.quality||'Standard',steps:p.steps||[],materials:p.materials||[]}));

let tab='home',photo='',diagnosed=false,problem='Humidité / moisissure',wizard=null;
let messages=[['bot','Bonjour 👋 Je suis ton Coach chantier. Pose-moi une question sur ton projet, les matériaux ou l’ordre des travaux.']];
const nav=[['home','🏠','Accueil'],['projects','📋','Chantiers'],['calc','🧮','Calculs'],['diagnostic','📸','Photo'],['coach','💬','Coach']];

function progress(p){return p.steps?.length?Math.round(p.steps.filter(x=>x[1]).length/p.steps.length*100):0}
function img(cat){return images[cat]||heroImg}
function save(){localStorage.setItem('bricoach-projects',JSON.stringify(projects))}
function go(t){tab=t;wizard=null;render();window.scrollTo({top:0,behavior:'smooth'})}

function shell(content){return `<div class="shell"><aside class="side"><div class="brand"><span class="logo">🔨</span>Bricoach</div><div class="tag">Ton chantier, étape par étape</div><div class="nav">${nav.map(n=>`<button class="${tab===n[0]?'active':''}" onclick="go('${n[0]}')"><span>${n[1]}</span>${n[2]}</button>`).join('')}</div><div class="sideFoot"><b>💡 Conseil du Coach</b><br>Un bon chantier commence par le bon ordre des étapes.</div></aside><main class="main"><div class="top"><div><div class="eyebrow">MON COACH TRAVAUX</div><h1>${tab==='home'?'Bonjour 👋':nav.find(n=>n[0]===tab)[2]}</h1></div><div class="avatar">BC</div></div>${content}</main><nav class="bottom">${nav.map(n=>`<button class="${tab===n[0]?'active':''}" onclick="go('${n[0]}')"><span>${n[1]}</span>${n[2]}</button>`).join('')}</nav></div>`}

function home(){let p=projects[0];return `<section class="hero"><div class="heroCopy"><div class="eyebrow heroEye">TON CHANTIER, BIEN ACCOMPAGNÉ</div><h2>Planifie. Réalise.<br><span>Profite.</span></h2><p>Décris ton projet et Bricoach te prépare un chantier structuré : ordre des travaux, quantités, budget et liste de courses.</p><div class="heroActions"><button class="btn primary" onclick="startWizard()">＋ Démarrer un chantier</button><button class="btn glass" onclick="go('diagnostic')">📸 J’ai un problème</button></div><div class="heroTrust"><span>✓ Parcours guidé</span><span>✓ Plan personnalisé</span><span>✓ Sauvegarde du chantier</span></div></div><div class="heroVisual"><img src="${heroImg}" alt="Rénovation intérieure Bricoach"><div class="heroFloat"><span class="floatIcon">✓</span><div><b>${projects.length} chantier${projects.length>1?'s':''} en cours</b><small>Reprends exactement où tu t’es arrêté.</small></div></div></div></section>
<section class="sectionBlock"><div class="sectionTitle"><div><div class="eyebrow">CHOISIS TON PROJET</div><h2>Un accompagnement adapté au chantier</h2></div><div class="muted">Choisis un métier pour démarrer directement l’assistant.</div></div><div class="tradeGrid">${Object.entries(meta).map(([cat,m])=>`<button class="tradeCard" onclick="startWizard('${cat}')"><img src="${img(cat)}" loading="lazy" alt="${m[0]}"><span class="tradeShade"></span><span class="tradeText"><b>${m[0]}</b><small>${m[1]}</small></span></button>`).join('')}</div></section>
<div class="grid"><div class="card quick visualQuick" onclick="go('diagnostic')"><img src="${diagImg}" loading="lazy" alt="Diagnostic chantier"><div class="quickOverlay"><div class="quickIcon">📸</div><div><h3>Montre-moi ton problème</h3><div>Photo + diagnostic guidé</div></div></div></div><div class="card quick" onclick="go('calc')"><div class="quickIcon">🧮</div><div><h3>Calculer mes matériaux</h3><div class="muted">Quantités, pertes et liste de courses</div></div></div><div class="card quick" onclick="go('coach')"><div class="quickIcon">💬</div><div><h3>Demander au Coach</h3><div class="muted">Une question sur ton chantier ?</div></div></div>${p?featuredProject(p):''}</div>`}

function featuredProject(p){return `<div class="card project featuredProject"><div class="projectMedia"><img src="${img(p.category)}" alt="${esc(p.category)}"><span class="projectMediaShade"></span><div class="projectMediaTitle"><span class="pill">${esc(p.category)}</span><h3>${esc(p.title)}</h3></div></div><div class="projectBody"><div class="sectionHead"><div><div class="muted small">${esc(p.room||'CHANTIER PRIORITAIRE')}</div><b>${progress(p)}% terminé</b></div><button class="btn soft" onclick="go('projects')">Continuer →</button></div><div class="progress"><span style="width:${progress(p)}%"></span></div><div class="steps">${p.steps.slice(0,4).map((s,i)=>`<div class="step"><span class="dot ${s[1]?'done':''}">${s[1]?'✓':i+1}</span>${esc(s[0])}</div>`).join('')}</div></div></div><div class="card stats"><h3>Vue rapide</h3><div class="metric"><span class="muted">⏱ Avancement</span><b>${progress(p)}%</b></div><div class="metric"><span class="muted">€ Budget</span><b>${Number(p.budget||0).toLocaleString('fr-FR')} €</b></div><div class="metric"><span class="muted">☑ Étapes</span><b>${p.steps.filter(x=>x[1]).length}/${p.steps.length}</b></div></div>`}

function projectsPage(){return `<div class="sectionHead pageTitle"><div><h2>Mes chantiers</h2><div class="muted">Avance étape par étape sans rien oublier.</div></div><button class="btn primary" onclick="startWizard()">＋ Nouveau chantier</button></div><div class="cards2">${projects.map(p=>`<div class="card projectCard"><div class="projectMedia compact"><img src="${img(p.category)}" loading="lazy" alt="${esc(p.category)}"><span class="projectMediaShade"></span><div class="projectMediaTitle"><span class="pill">${esc(p.category)}</span><h3>${esc(p.title)}</h3></div></div><div class="projectBody"><div class="projectMeta"><span>${esc(p.room||'Pièce')}</span><span>${esc(p.level||'Débutant')}</span><span>${Number(p.area||0)} m²</span></div><div class="sectionHead"><span class="muted">Budget ${Number(p.budget||0).toLocaleString('fr-FR')} €</span><b>${progress(p)}%</b></div><div class="progress"><span style="width:${progress(p)}%"></span></div><div class="steps">${p.steps.map((s,i)=>`<button class="step" onclick="toggleStep(${p.id},${i})"><span class="dot ${s[1]?'done':''}">${s[1]?'✓':i+1}</span>${esc(s[0])}</button>`).join('')}</div></div></div>`).join('')}</div>`}
function toggleStep(id,i){let p=projects.find(x=>x.id===id);if(!p)return;p.steps[i][1]=p.steps[i][1]?0:1;save();render()}

function calcPage(){return `<div class="pageTitle"><h2>Calculateur matériaux</h2><div class="muted">Une estimation simple et transparente.</div></div><div class="cards2"><div class="card calcCard"><div class="calcCover"><img src="${images.Carrelage}" alt="Carrelage"></div><h3>Calcul express carrelage</h3><div class="field"><label>Surface nette (m²)</label><input id="surface" type="number" min="0" step="0.1" value="20" oninput="recalc()"></div><div class="field"><label>Marge de perte (%)</label><input id="loss" type="number" min="0" max="40" value="10" oninput="recalc()"></div><div id="calcResult" class="diagnostic"></div></div><div class="card"><h3>Listes de courses</h3>${projects.map(p=>`<div class="shopping"><b>${esc(p.title)}</b>${p.materials.map((m,i)=>`<label class="shopItem ${m[2]?'done':''}"><input type="checkbox" ${m[2]?'checked':''} onchange="toggleMat(${p.id},${i})"><span>${esc(m[0])}</span><b>${esc(m[1])}</b></label>`).join('')}</div>`).join('')}</div></div>`}
function recalc(){let s=Number($('#surface')?.value||20),l=Number($('#loss')?.value||10),order=s*(1+l/100),glue=Math.ceil(s/5),el=$('#calcResult');if(el)el.innerHTML=`<b>À commander : ${order.toFixed(1)} m²</b><br><span class="muted">Colle estimative : ${glue} sacs de 25 kg. À ajuster selon format, support et rendement fabricant.</span>`}
function toggleMat(id,i){let p=projects.find(x=>x.id===id);if(!p||!p.materials[i])return;p.materials[i][2]=p.materials[i][2]?0:1;save();render()}

function diagPage(){return `<div class="pageTitle"><h2>📸 Montre-moi ton chantier</h2><div class="muted">Ajoute une photo puis choisis le type de problème.</div></div><div class="diagHero"><img src="${diagImg}" alt="Diagnostic chantier"><div><div class="eyebrow">ASSISTANCE CHANTIER</div><h3>Un problème ? Commence par observer avant de réparer.</h3><p>Bricoach structure les vérifications et te signale les situations où un professionnel est préférable.</p></div></div><div class="cards2"><div class="card"><div class="upload"><div class="camera">📷</div><h3>Prendre ou ajouter une photo</h3><input type="file" accept="image/*" capture="environment" onchange="loadPhoto(event)">${photo?`<img class="preview" src="${photo}">`:''}</div><div class="field"><label>Type de problème</label><select onchange="problem=this.value;diagnosed=false"><option>Humidité / moisissure</option><option>Fissure</option><option>Carrelage décollé</option><option>Fuite d’eau</option><option>Électricité</option></select></div><button class="btn primary full" ${photo?'':'disabled'} onclick="diagnosed=true;render()">✨ Analyser le problème</button></div><div class="card"><h3>Diagnostic guidé</h3>${diagnosed?diagnosticText():`<div class="empty">Le résultat apparaîtra ici après l’ajout d’une photo.</div>`}</div></div>`}
function loadPhoto(e){let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{photo=r.result;diagnosed=false;render()};r.readAsDataURL(f)}
function diagnosticText(){let t='Contrôle recommandé',b='Observe la zone et identifie la cause avant toute réparation définitive.',danger=false;if(problem.includes('Humidité')){t='Traces compatibles avec un problème d’humidité';b='Vérifie si la trace augmente après la pluie, s’il existe une canalisation proche et si la ventilation est correcte.'}if(problem==='Fissure'){t='Fissure à qualifier';b='Mesure sa largeur et surveille son évolution. Une fissure active, large ou traversante mérite un avis professionnel.'}if(problem.includes('Carrelage')){t='Décollement possible';b='Teste doucement les carreaux voisins. S’ils bougent ou sonnent creux, contrôle le support et le collage.'}if(problem.includes('Fuite')){t='Suspicion de fuite';b='Coupe l’eau si la fuite est active et identifie l’origine avant toute remise en état.';danger=true}if(problem.includes('Électricité')){t='Intervention électrique';b='Coupe le circuit au tableau et ne démonte pas une installation sous tension.';danger=true}return `<div class="diagnostic ${danger?'danger':''}"><b>${danger?'⚠️':'🔎'} ${t}</b><p>${b}</p><div class="small">Diagnostic indicatif : ne remplace pas le contrôle d’un professionnel lorsqu’il existe un risque.</div></div>`}

function coachPage(){return `<div class="pageTitle"><h2>Coach chantier</h2><div class="muted">Le Coach utilise le contexte du chantier principal.</div></div><div class="card"><div class="chat" id="chat">${messages.map(m=>`<div class="bubble ${m[0]}">${esc(m[1])}</div>`).join('')}</div><form class="chatForm" onsubmit="coach(event)"><input id="msg" placeholder="Ex : quelle colle pour ma douche ?"><button class="btn primary">Envoyer</button></form></div>`}
function coach(e){e.preventDefault();let q=$('#msg').value.trim();if(!q)return;let p=projects[0]||starter,l=q.toLowerCase(),a='Avance étape par étape et vérifie les préconisations du fabricant.';if(l.includes('colle'))a=`Pour ${p.category.toLowerCase()}, choisis la colle selon le support, le format et l’usage. Ton chantier fait ${p.area} m².`;if(l.includes('étanch'))a='En douche, traite les angles, jonctions et passages de tuyaux puis respecte le temps de séchage.';if(l.includes('budget'))a=`Le budget enregistré pour « ${p.title} » est de ${p.budget} €. Prévois 10 à 15 % de marge.`;messages.push(['user',q],['bot',a]);render();setTimeout(()=>{let c=$('#chat');if(c)c.scrollTop=c.scrollHeight},0)}

function startWizard(category=''){wizard={step:0,data:{category,room:'',name:'',area:12,level:'Débutant',budget:750,quality:'Standard'}};if(category)wizard.step=1;render()}
function closeWizard(){wizard=null;render()}
function setW(field,value){if(!wizard)return;wizard.data[field]=value;render()}
function syncW(field,value){if(wizard)wizard.data[field]=value}
function wizardNext(){if(!wizard)return;let d=wizard.data;if(wizard.step===0&&!d.category)return;if(wizard.step===1&&!d.room)return;if(wizard.step===2&&(!Number(d.area)||Number(d.area)<=0))return;wizard.step=Math.min(5,wizard.step+1);render()}
function wizardBack(){if(!wizard)return;wizard.step=Math.max(0,wizard.step-1);render()}

function wizardMarkup(){if(!wizard)return'';let d=wizard.data,step=wizard.step,total=6;let body='';
if(step===0)body=`<div class="wizardChoices trades">${Object.entries(meta).map(([cat,m])=>`<button class="wizardChoice ${d.category===cat?'selected':''}" onclick="setW('category','${cat}');wizardNext()"><span class="choiceIcon">${m[2]}</span><span><b>${m[0]}</b><small>${m[1]}</small></span></button>`).join('')}</div>`;
if(step===1)body=`<div class="wizardIntro"><h3>Dans quelle pièce travailles-tu ?</h3><p>La pièce permet d’adapter les étapes du chantier.</p></div><div class="wizardChoices rooms">${rooms.map(r=>`<button class="wizardChoice compact ${d.room===r?'selected':''}" onclick="setW('room','${r}')"><b>${r}</b></button>`).join('')}</div><div class="field"><label>Nom du chantier <span class="optional">(facultatif)</span></label><input value="${esc(d.name)}" placeholder="Ex : Salle de bain principale" oninput="syncW('name',this.value)"></div>`;
if(step===2)body=`<div class="wizardIntro"><h3>Quelle surface vas-tu traiter ?</h3><p>${surfaceHelp(d.category)}</p></div><div class="bigNumber"><input type="number" min="0.5" step="0.5" value="${Number(d.area)||''}" oninput="syncW('area',this.value)"><span>m²</span></div><div class="wizardHint">💡 Tu pourras affiner les dimensions dans les calculateurs métier.</div>`;
if(step===3)body=`<div class="wizardIntro"><h3>Quel est ton niveau ?</h3><p>Bricoach adaptera le niveau de détail des conseils.</p></div><div class="wizardChoices">${levels.map(l=>`<button class="wizardChoice ${d.level===l[0]?'selected':''}" onclick="setW('level','${l[0]}')"><span><b>${l[0]}</b><small>${l[1]}</small></span>${d.level===l[0]?'<span class="check">✓</span>':''}</button>`).join('')}</div>`;
if(step===4)body=`<div class="wizardIntro"><h3>Quel budget et quelle gamme ?</h3><p>Le budget sert de repère pour suivre ton chantier.</p></div><div class="field"><label>Budget cible</label><div class="moneyInput"><input type="number" min="0" step="50" value="${Number(d.budget)||0}" oninput="syncW('budget',this.value)"><span>€</span></div></div><div class="qualityGrid">${qualities.map(q=>`<button class="quality ${d.quality===q[0]?'selected':''}" onclick="setW('quality','${q[0]}')"><b>${q[0]}</b><small>${q[1]}</small></button>`).join('')}</div>`;
if(step===5)body=wizardSummary(d);
let canNext=!(step===0&&!d.category||step===1&&!d.room||step===2&&(!Number(d.area)||Number(d.area)<=0));
return `<div class="wizardBackDrop" role="dialog" aria-modal="true"><div class="wizard"><div class="wizardTop"><div><div class="eyebrow">CRÉATION DU CHANTIER</div><h2>${stepTitle(step)}</h2></div><button class="wizardClose" onclick="closeWizard()" aria-label="Fermer">✕</button></div><div class="wizardProgress"><span style="width:${((step+1)/total)*100}%"></span></div><div class="wizardCount">Étape ${step+1} sur ${total}</div><div class="wizardBody">${body}</div><div class="wizardFooter">${step>0?`<button class="btn soft" onclick="wizardBack()">← Retour</button>`:'<span></span>'}${step<5?`<button class="btn primary" ${canNext?'':'disabled'} onclick="wizardNext()">Continuer →</button>`:`<button class="btn primary" onclick="createFromWizard()">✓ Créer mon chantier</button>`}</div></div></div>`}
function stepTitle(s){return['Type de travaux','La pièce','La surface','Ton expérience','Budget & gamme','Ton plan est prêt'][s]}
function surfaceHelp(cat){return cat==='Peinture'?'Indique la surface totale des murs/plafonds à peindre.':cat==='Placo / isolation'?'Indique la surface de cloison ou doublage à réaliser.':cat==='Sol / parquet'?'Indique la surface au sol à couvrir.':'Indique la surface totale à carreler.'}
function wizardSummary(d){let plan=buildPlan(d);return `<div class="summaryHero"><img src="${img(d.category)}" alt="${esc(d.category)}"><span></span><div><b>${esc(d.name||`${d.room} · ${d.category}`)}</b><small>${esc(d.category)} · ${esc(d.room)}</small></div></div><div class="summaryGrid"><div><span>Surface</span><b>${Number(d.area)} m²</b></div><div><span>Niveau</span><b>${esc(d.level)}</b></div><div><span>Budget</span><b>${Number(d.budget||0).toLocaleString('fr-FR')} €</b></div><div><span>Gamme</span><b>${esc(d.quality)}</b></div></div><div class="summaryPlan"><div class="eyebrow">PLAN GÉNÉRÉ</div>${plan.steps.slice(0,5).map((s,i)=>`<div><span>${i+1}</span>${esc(s[0])}</div>`).join('')}<small>+ liste de courses calculée automatiquement</small></div>`}

function buildPlan(d){let a=Math.max(.5,Number(d.area)||1),steps=[],materials=[];
if(d.category==='Carrelage'){steps=[['Protection et préparation',0],['Contrôle et préparation des supports',0]];if(d.room==='Salle de bain')steps.push(['Étanchéité des zones humides',0]);steps.push(['Calepinage et traçage',0],['Préparation de la colle',0],['Pose du carrelage',0],['Joints et silicones',0],['Nettoyage et réception',0]);materials=[['Carrelage',`${(a*1.10).toFixed(1)} m²`,0],['Colle adaptée',`${Math.ceil(a/5)} sacs de 25 kg`,0],['Joint',`${Math.max(2,Math.ceil(a*.25))} kg`,0],['Croisillons / cales',`${Math.ceil(a*15)} pièces`,0]];if(d.room==='Salle de bain')materials.push(['Système d’étanchéité','1 kit selon surface',0]);}
if(d.category==='Peinture'){steps=[['Protection de la pièce',0],['Nettoyage et contrôle du support',0],['Rebouchage et réparations',0],['Ponçage et dépoussiérage',0],['Sous-couche si nécessaire',0],['Première couche',0],['Deuxième couche',0],['Retouches et nettoyage',0]];materials=[['Peinture finition',`${Math.ceil(a*2/10)} L env.`,0],['Sous-couche',`${Math.ceil(a/10)} L env.`,0],['Enduit de rebouchage',`${Math.max(1,Math.ceil(a/20))} sac/pot`,0],['Protection et consommables','1 lot',0]];}
if(d.category==='Sol / parquet'){steps=[['Dépose et nettoyage',0],['Contrôle de la planéité',0],['Acclimatation du revêtement',0],['Pose de la sous-couche',0],['Calepinage et départ',0],['Pose du sol',0],['Plinthes et seuils',0],['Nettoyage final',0]];materials=[['Revêtement',`${(a*1.08).toFixed(1)} m²`,0],['Sous-couche',`${Math.ceil(a*1.05)} m²`,0],['Cales de dilatation','1 lot',0],['Plinthes','À mesurer selon périmètre',0]];}
if(d.category==='Placo / isolation'){steps=[['Traçage de l’implantation',0],['Pose des rails',0],['Pose des montants',0],['Passage des réseaux',0],['Mise en place de l’isolant',0],['Pose des plaques',0],['Bandes et enduits',0],['Ponçage et contrôle',0]];materials=[['Plaques de plâtre',`${Math.ceil(a/3)} plaques env.`,0],['Rails / montants','À affiner selon dimensions',0],['Isolant',`${Math.ceil(a*1.05)} m²`,0],['Vis placo',`${Math.ceil(a*20)} pièces env.`,0],['Bandes + enduit','1 lot',0]];}
return{steps,materials}}

function createFromWizard(){if(!wizard)return;let d=wizard.data,plan=buildPlan(d);let title=(d.name||`${d.room} · ${d.category}`).trim();projects.unshift({id:Date.now(),title,category:d.category,room:d.room,area:Number(d.area),level:d.level,quality:d.quality,budget:Number(d.budget)||0,steps:plan.steps,materials:plan.materials,createdAt:new Date().toISOString()});save();wizard=null;tab='projects';render();window.scrollTo({top:0,behavior:'smooth'})}

function render(){let c=tab==='home'?home():tab==='projects'?projectsPage():tab==='calc'?calcPage():tab==='diagnostic'?diagPage():coachPage();let app=$('#app');if(app)app.innerHTML=shell(c)+(wizard?wizardMarkup():'');if(tab==='calc')setTimeout(recalc,0);document.body.classList.toggle('modalOpen',!!wizard)}
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&wizard)closeWizard()});
render();