const V18_LEVELS=['Débutant','Bricoleur','Confirmé','Expert'];
if(!v15Profile.skills||typeof v15Profile.skills!=='object'){
  const old=v15Profile.level||'Bricoleur';
  v15Profile.skills={};V14_WORKS.forEach(c=>v15Profile.skills[c]=old);
}
V14_WORKS.forEach(c=>{if(!v15Profile.skills[c])v15Profile.skills[c]='Bricoleur'});
function v18Level(cat){return v15Profile.skills[cat]||'Bricoleur'}
function v18Save(){try{localStorage.setItem('bricoach-user-profile-v15',JSON.stringify(v15Profile))}catch(_){}}
function v18ProfileTop(){return document.querySelector('#v15ProfileModal .v15ProfileModal')?.scrollTop||0}
function v18Restore(top){requestAnimationFrame(()=>requestAnimationFrame(()=>{const e=document.querySelector('#v15ProfileModal .v15ProfileModal');if(e)e.scrollTop=top}))}
function v18SetLevel(cat,level){const top=v18ProfileTop();v15Profile.skills[cat]=level;if(!v15Profile.interests.includes(cat))v15Profile.interests.push(cat);v18Save();v15RenderProfileModal();v18Restore(top)}
function v15ToggleInterest(cat){const top=v18ProfileTop(),i=v15Profile.interests.indexOf(cat);i>=0?v15Profile.interests.splice(i,1):v15Profile.interests.push(cat);v18Save();v15RenderProfileModal();v18Restore(top)}
function v15SaveProfile(){v18Save()}
function v15RenderProfileModal(){
  const top=v18ProfileTop();document.querySelector('#v15ProfileModal')?.remove();
  const cards=V14_WORKS.map(c=>{const on=v15Profile.interests.includes(c),lv=v18Level(c);return `<section class="v18SkillCard ${on?'selected':''}"><div class="v18SkillTop"><span class="v18SkillIcon">${meta[c]?.[2]||'🔧'}</span><div><b>${esc(c)}</b><small>${on?`Niveau : ${esc(lv)}`:'Non sélectionné'}</small></div><button class="v18Toggle" onclick='v15ToggleInterest(${JSON.stringify(c)})'>${on?'✓ Sélectionné':'＋ Ajouter'}</button></div>${on?`<div class="v18Levels">${V18_LEVELS.map(l=>`<button class="v18Level ${lv===l?'active':''}" onclick='v18SetLevel(${JSON.stringify(c)},${JSON.stringify(l)})'>${l}</button>`).join('')}</div>`:''}</section>`}).join('');
  document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="v15ProfileModal"><div class="modal v15ProfileModal"><div class="wizardTop"><div><div class="eyebrow">MON PROFIL BRICOLAGE</div><h2>Mes compétences par métier</h2></div><button class="close" onclick="document.querySelector('#v15ProfileModal').remove()">✕</button></div><div class="v18ProfileIntro"><b>Un niveau différent pour chaque métier</b><div>Exemple : Expert en carrelage et Débutant en peinture. Les tutoriels et conseils s’adaptent séparément.</div></div><div class="v18SkillList">${cards}</div><div class="v15ProfileNote">💡 Ces niveaux appartiennent à ton profil et peuvent être modifiés à tout moment.</div><button class="btn primary full" onclick="v15SaveProfile();document.querySelector('#v15ProfileModal').remove();render()">✓ Enregistrer mon profil</button></div></div>`);if(top)v18Restore(top)
}
try{const b=v14WorkDefaults;v14WorkDefaults=function(c,r=''){const w=b(c,r);w.level=v18Level(c);return w}}catch(_){}
try{const b=v14Step3;v14Step3=function(){return b().replace(/Profil : [^<]+/,'Niveaux définis par métier').replace(/Les tutoriels seront adaptés à ce niveau\./,'Chaque tutoriel utilise le niveau du métier concerné.')}}catch(_){}
try{const b=v14Step5;v14Step5=function(){return b().replace(/Tutoriels adaptés à ton profil [^<]+/,'Tutoriels adaptés métier par métier').replace(/Le niveau n’est pas enregistré dans ce chantier[^<]+/,'Carrelage, peinture, sol et placo utilisent chacun le niveau défini dans ton profil.')}}catch(_){}
function v18Tutorial(category,level){const t=v15TutorialText(category,level==='Expert'?'Confirmé':level);if(level==='Expert')t.intro='Version expert : contrôles critiques, compatibilités, tolérances et points de vigilance uniquement.';return t}
function openAdaptiveTutorial(projectId,locId,workId){const p=projects.find(x=>x.id===projectId),l=p?.locations?.find(x=>x.id===locId),w=l?.works?.find(x=>x.id===workId);if(!w)return;const level=v18Level(w.category),t=v18Tutorial(w.category,level),steps=w.steps||[];document.querySelector('#v15TutorialModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="v15TutorialModal"><div class="modal v15TutorialModal"><div class="wizardTop"><div><div class="eyebrow">TUTORIEL ${esc(level).toUpperCase()}</div><h2>${meta[w.category]?.[2]||'🔧'} ${esc(w.category)} · ${esc(l.name)}</h2></div><button class="close" onclick="document.querySelector('#v15TutorialModal').remove()">✕</button></div><div class="v15TutorIntro"><b>${esc(level)}</b><span>${esc(t.intro)}</span><button class="btn soft" onclick="document.querySelector('#v15TutorialModal').remove();openProfileSettings()">Modifier mon niveau</button></div><div class="v15TutorSteps">${steps.map((s,i)=>`<section><span>${i+1}</span><div><b>${esc(s[0])}</b><small>${level==='Débutant'?'Explication détaillée et validation avant de poursuivre.':level==='Expert'?'Contrôle critique avant enchaînement.':'Vérifie le résultat avant l’étape suivante.'}</small></div></section>`).join('')}</div><div class="v15TutorTips"><h3>Points de vigilance</h3>${t.tips.map(x=>`<div>✓ ${esc(x)}</div>`).join('')}</div></div></div>`)}
try{const b=projectCard;projectCard=function(p){return b(p).replace(/🎓 Tutoriel (Débutant|Bricoleur|Confirmé|Expert)/g,'🎓 Tutoriel adapté')}}catch(_){}
v18Save();try{render()}catch(_){}