const V15_PROFILE_KEY='bricoach-user-profile-v15';
let v15Profile={level:'Bricoleur',interests:['Carrelage','Peinture','Sol / parquet','Placo / isolation']};
try{const x=JSON.parse(localStorage.getItem(V15_PROFILE_KEY)||'null');if(x)v15Profile={...v15Profile,...x,interests:Array.isArray(x.interests)?x.interests:v15Profile.interests}}catch(_){}
function v15SaveProfile(){try{localStorage.setItem(V15_PROFILE_KEY,JSON.stringify(v15Profile))}catch(_){}}
function v15ToggleInterest(cat){const i=v15Profile.interests.indexOf(cat);if(i>=0)v15Profile.interests.splice(i,1);else v15Profile.interests.push(cat);v15RenderProfileModal()}
function v15SetProfileLevel(level){v15Profile.level=level;v15RenderProfileModal()}
function v15RenderProfileModal(){
  document.querySelector('#v15ProfileModal')?.remove();
  document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="v15ProfileModal"><div class="modal v15ProfileModal"><div class="wizardTop"><div><div class="eyebrow">MON PROFIL BRICOLAGE</div><h2>Personnalise Bricoach</h2></div><button class="close" onclick="document.querySelector('#v15ProfileModal').remove()">✕</button></div><p class="muted">Ce niveau est global : il ne dépend pas d’un chantier. Il sert à adapter les tutoriels, le vocabulaire, les rappels de sécurité et le niveau de détail.</p><div class="field"><label>Mon niveau</label><div class="v15LevelGrid">${[['Débutant','🌱','Je veux être guidé pas à pas.'],['Bricoleur','🔧','Je connais les bases et je veux les points importants.'],['Confirmé','🛠️','Je veux surtout les contrôles techniques et les points de vigilance.']].map(x=>`<button class="v15Level ${v15Profile.level===x[0]?'selected':''}" onclick="v15SetProfileLevel('${x[0]}')"><span>${x[1]}</span><b>${x[0]}</b><small>${x[2]}</small></button>`).join('')}</div></div><div class="field"><label>Postes qui m’intéressent</label><div class="v15InterestGrid">${V14_WORKS.map(c=>`<button class="v15Interest ${v15Profile.interests.includes(c)?'selected':''}" onclick='v15ToggleInterest(${JSON.stringify(c)})'><span>${meta[c]?.[2]||'🔧'}</span><b>${esc(c)}</b><small>${v15Profile.interests.includes(c)?'Sélectionné':'Ajouter'}</small></button>`).join('')}</div></div><div class="v15ProfileNote">💡 Lors de la création d’un compte, ces choix pourront être demandés une seule fois puis modifiés ici à tout moment.</div><button class="btn primary full" onclick="v15SaveProfile();document.querySelector('#v15ProfileModal').remove();render()">✓ Enregistrer mon profil</button></div></div>`);
}
function openProfileSettings(){v15RenderProfileModal()}

try{
  const v15BaseShell=shell;
  shell=function(content){return v15BaseShell(content).replace('<div class="avatar">BC</div>',`<button class="avatar v15Avatar" onclick="openProfileSettings()" title="Mon profil">${v15Profile.level==='Débutant'?'🌱':v15Profile.level==='Confirmé'?'🛠️':'🔧'}</button>`)};
}catch(_){}

try{
  const v15BaseDefaults=v14WorkDefaults;
  v14WorkDefaults=function(category,room=''){const w=v15BaseDefaults(category,room);w.level=v15Profile.level;return w};
}catch(_){}

function v15SortedWorks(){
  const fav=new Set(v15Profile.interests||[]);
  return [...V14_WORKS].sort((a,b)=>(fav.has(b)?1:0)-(fav.has(a)?1:0));
}
function v14Step3(){return `<div class="v14Intro"><div class="v14IntroIcon">🧰</div><h3>Que fais-tu dans chaque lieu ?</h3><p>Choisis un ou plusieurs postes par pièce et renseigne ses mesures. Tes métiers favoris apparaissent en premier.</p></div><div class="v15ProfileInline"><span>${v15Profile.level==='Débutant'?'🌱':v15Profile.level==='Confirmé'?'🛠️':'🔧'}</span><div><b>Profil : ${esc(v15Profile.level)}</b><small>Les tutoriels seront adaptés à ce niveau.</small></div><button class="btn soft" onclick="openProfileSettings()">Modifier</button></div><div class="v14LocationList">${wizard.locations.map((l,li)=>`<section class="v14LocationCard"><div class="v14LocationTitle"><span>${li+1}</span><div><b>${esc(l.name)}</b><small>${l.works.length} poste${l.works.length>1?'s':''} sélectionné${l.works.length>1?'s':''}</small></div></div><div class="v14Dims"><label>Longueur<input type="number" step="0.1" min="0" value="${l.length||''}" placeholder="m" onchange="v14SetLocation(${li},'length',this.value)"></label><label>Largeur<input type="number" step="0.1" min="0" value="${l.width||''}" placeholder="m" onchange="v14SetLocation(${li},'width',this.value)"></label><label>Hauteur<input type="number" step="0.1" min="0" value="${l.height||2.5}" placeholder="m" onchange="v14SetLocation(${li},'height',this.value)"></label><label>Ouvertures<input type="number" step="0.1" min="0" value="${l.openings||''}" placeholder="m²" onchange="v14SetLocation(${li},'openings',this.value)"></label></div>${l.length&&l.width?`<div class="v14CalcHint">Sol : <b>${v14LocationFloor(l).toFixed(1)} m²</b>${l.height?` · Murs nets : <b>${v14LocationWalls(l).toFixed(1)} m²</b>`:''}</div>`:''}<div class="v14WorkPicker">${v15SortedWorks().map(c=>`<button class="v14WorkPick ${l.works.some(w=>w.category===c)?'selected':''}" onclick='v14ToggleWork(${li},${JSON.stringify(c)})'><span>${meta[c]?.[2]||'🔧'}</span><b>${esc(c)}</b><small>${l.works.some(w=>w.category===c)?'Sélectionné':v15Profile.interests.includes(c)?'Favori':'Ajouter'}</small></button>`).join('')}</div>${!l.works.length?'<div class="v14ErrorHint">Choisis au moins un travail pour ce lieu.</div>':''}</section>`).join('')}</div>`}

function v14CommonWork(q){const s=v14SuggestedArea(q.loc,q.work);return `<div class="v14WorkHeader"><div><span>${esc(q.loc.name)}</span><h3>${esc(q.work.category)}</h3></div><strong>Poste ${wizard.detailIndex+1}/${v14Queue().length}</strong></div><div class="v14MeasureSuggestion"><div><b>Surface du poste</b><small>${s>0?`Calcul d’après les mesures du lieu : ${s.toFixed(1)} m²`:'Pas assez de mesures pour calculer automatiquement.'}</small></div>${s>0?`<button class="btn soft" onclick="v14UseSuggested()">Utiliser ${s.toFixed(1)} m²</button>`:''}</div><div class="field"><label>Surface à traiter</label><div class="bigInput v14Area"><input type="number" min="0.5" step="0.5" value="${Number(q.work.area)||''}" oninput="v14Current().work.area=Number(this.value)||0"><span>m²</span></div></div><div class="field"><label>Gamme de produits</label>${v14RangeChoices(q.work)}</div><div class="v15AutoBudget"><span>🧾</span><div><b>Budget calculé automatiquement</b><small>Tu ne saisis plus un budget arbitraire. Bricoach l’estime à partir de la surface, de la gamme et des produits nécessaires.</small></div></div>`}

function v14Step5(){
  const total=v14ProjectEstimate({locations:wizard.locations});return `<div class="v14SummaryHead"><div><span>PROJET PRÊT À ENREGISTRER</span><h3>${esc(wizard.title||'Mon projet travaux')}</h3><p>${esc(wizard.projectType)} · ${wizard.locations.length} lieu${wizard.locations.length>1?'x':''} · ${v14Queue().length} poste${v14Queue().length>1?'s':''}</p></div><strong>≈ ${total.toLocaleString('fr-FR')} €</strong></div><div class="v15EstimateExplainer"><b>🧾 Estimation automatique</b><span>Ce montant vient des surfaces et des gammes choisies. Il sera affiné avec les références et magasins dans « Chiffrage » après enregistrement.</span></div><div class="v14SummaryLocations">${wizard.locations.map(l=>`<section><div class="v14SummaryLocTitle"><b>📍 ${esc(l.name)}</b><small>${l.length&&l.width?`${l.length} × ${l.width} × ${l.height||2.5} m`:''}</small></div>${l.works.map(w=>`<div class="v14SummaryWork"><div><b>${meta[w.category]?.[2]||'🔧'} ${esc(w.category)}</b><small>${Number(w.area).toFixed(1)} m² · ${esc(w.range)}</small></div><strong>≈ ${v14EstimateWork(w).toLocaleString('fr-FR')} €</strong></div>`).join('')}</section>`).join('')}</div><div class="v15ProfileSummary"><span>${v15Profile.level==='Débutant'?'🌱':v15Profile.level==='Confirmé'?'🛠️':'🔧'}</span><div><b>Tutoriels adaptés à ton profil ${esc(v15Profile.level)}</b><small>Le niveau n’est pas enregistré dans ce chantier : il vient de ton profil et peut changer à tout moment.</small></div></div><div class="validationNote">✓ Rien n’est enregistré avant d’appuyer sur <b>${wizard.editId?'Enregistrer les modifications':'Créer et enregistrer'}</b>. Tu pourras ensuite modifier les lieux ou les postes.</div>`}

function v15TutorialText(category,level){
  const intro={Débutant:'Je t’explique chaque étape, avec le pourquoi, les outils et les erreurs à éviter.',Bricoleur:'Je vais à l’essentiel avec les contrôles importants et les points de vigilance.',Confirmé:'Version synthétique : contrôles techniques, tolérances et points critiques.'}[level]||'';
  const tips={
    Carrelage:['Contrôle la planéité et la cohésion du support avant de commencer.','Fais un calepinage à sec pour éviter les petites coupes disgracieuses.','Respecte le temps ouvert de la colle et le double encollage quand le format/support l’exige.','Ne joins pas trop tôt et respecte les joints périphériques / fractionnement.'],
    Peinture:['Le résultat dépend surtout de la préparation du support.','Traite fissures, trous et reprises avant sous-couche.','Respecte le rendement fabricant plutôt que de trop tirer la peinture.','Croise les passes et termine dans le même sens.'],
    'Sol / parquet':['Contrôle humidité, planéité et propreté du support.','Laisse le revêtement s’acclimater si le fabricant le demande.','Respecte le jeu périphérique et les règles de pose du produit.','Vérifie les seuils, portes et sens de pose avant de démarrer.'],
    'Placo / isolation':['Trace précisément avant de fixer l’ossature.','Respecte entraxes, type de plaque et visserie adaptés.','Décale les joints lorsque le système le demande.','La qualité des bandes et de l’enduit conditionne la finition finale.']
  }[category]||['Prépare le support.','Respecte les prescriptions fabricant.','Contrôle chaque étape avant de poursuivre.'];
  return {intro,tips};
}
function openAdaptiveTutorial(projectId,locId,workId){
  const p=projects.find(x=>x.id===projectId),l=p?.locations?.find(x=>x.id===locId),w=l?.works?.find(x=>x.id===workId);if(!w)return;
  const t=v15TutorialText(w.category,v15Profile.level),steps=w.steps||[];
  document.querySelector('#v15TutorialModal')?.remove();
  document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="v15TutorialModal"><div class="modal v15TutorialModal"><div class="wizardTop"><div><div class="eyebrow">TUTORIEL ${esc(v15Profile.level).toUpperCase()}</div><h2>${meta[w.category]?.[2]||'🔧'} ${esc(w.category)} · ${esc(l.name)}</h2></div><button class="close" onclick="document.querySelector('#v15TutorialModal').remove()">✕</button></div><div class="v15TutorIntro"><b>${esc(v15Profile.level)}</b><span>${esc(t.intro)}</span><button class="btn soft" onclick="document.querySelector('#v15TutorialModal').remove();openProfileSettings()">Changer mon niveau</button></div><div class="v15TutorSteps">${steps.map((s,i)=>`<section><span>${i+1}</span><div><b>${esc(s[0])}</b><small>${v15Profile.level==='Débutant'?'Avance seulement quand cette étape est propre et contrôlée.':v15Profile.level==='Confirmé'?'Contrôle le point critique avant enchaînement.':'Vérifie le support et le résultat avant l’étape suivante.'}</small></div></section>`).join('')}</div><div class="v15TutorTips"><h3>Points de vigilance</h3>${t.tips.map(x=>`<div>✓ ${esc(x)}</div>`).join('')}</div></div></div>`);
}

function projectCard(p){p=v14SyncProject(p);const pr=v14ProjectProgress(p),estimate=v14ProjectEstimate(p);return `<div class="card projectCard v14ProjectCard"><div class="projectMedia compact"><img src="${img(p.category)}" loading="lazy" alt="${esc(p.category)}"><span class="projectMediaShade"></span><div class="projectMediaTitle"><span class="pill">${esc(p.projectType||'Projet travaux')}</span><h3>${esc(p.title)}</h3></div></div><div class="projectBody"><div class="v14ProjectStats"><span><b>${p.locations.length}</b> lieu${p.locations.length>1?'x':''}</span><span><b>${p.locations.flatMap(l=>l.works).length}</b> poste${p.locations.flatMap(l=>l.works).length>1?'s':''}</span><span><b>${p.area}</b> m² traités</span><span><b>${estimate.toLocaleString('fr-FR')} €</b> estimés</span></div><div class="sectionHead"><span class="muted">Avancement global</span><b>${pr}%</b></div><div class="progress"><span style="width:${pr}%"></span></div><div class="v14ProjectLocations">${p.locations.map(l=>`<details><summary><span>📍</span><b>${esc(l.name)}</b><small>${l.works.length} poste${l.works.length>1?'s':''}</small></summary><div>${l.works.map(w=>`<div class="v14ProjectWork"><div class="v14ProjectWorkHead"><span>${meta[w.category]?.[2]||'🔧'}</span><div><b>${esc(w.category)}</b><small>${Number(w.area).toFixed(1)} m² · ${esc(w.range)}</small></div><strong>${w.steps?.length?Math.round(w.steps.filter(s=>s[1]).length/w.steps.length*100):0}%</strong></div><div class="v15WorkTools"><button class="btn soft" onclick="openAdaptiveTutorial(${p.id},${l.id},${w.id})">🎓 Tutoriel ${esc(v15Profile.level)}</button></div><div class="steps">${(w.steps||[]).map((s,i)=>`<button class="step" onclick="toggleWorkStep(${p.id},${l.id},${w.id},${i})"><span class="dot ${s[1]?'done':''}">${s[1]?'✓':i+1}</span>${esc(s[0])}</button>`).join('')}</div></div>`).join('')}</div></details>`).join('')}</div><div class="projectActions projectActions3"><button class="btn soft" onclick="openWizard(null,${p.id})">✏️ Modifier</button><button class="btn soft" onclick="openLocalQuote(${p.id})">🧾 Chiffrage</button><button class="btn dangerBtn" onclick="askDelete(${p.id})">🗑️ Supprimer</button></div></div></div>`}
