/* Bricoach V21 — navigation, inventory UX, unified quote and interactive tutorials */

/* ---------- Navigation burger + Coach ---------- */
function v21PatchNavigation(){
  document.querySelectorAll('.bottom').forEach(e=>e.remove());
  const top=document.querySelector('.top');
  if(!top)return;
  const avatar=top.querySelector('.avatar');if(avatar)avatar.style.display='none';
  if(!top.querySelector('.v21TopActions')){
    top.insertAdjacentHTML('beforeend',`<div class="v21TopActions"><button class="v21Burger" onclick="v21OpenMenu()" aria-label="Menu">☰</button><button class="v21Coach" onclick="go('coach')">💬 <span>Coach</span></button></div>`);
  }
}
function v21MenuAction(action){document.querySelector('#v21Menu')?.remove();setTimeout(action,0)}
function v21OpenMenu(){
  document.querySelector('#v21Menu')?.remove();
  const items=[
    ['🏠','Accueil',"v21MenuAction(()=>go('home'))"],
    ['📋','Mes chantiers',"v21MenuAction(()=>go('projects'))"],
    ['🧮','Calculs',"v21MenuAction(()=>go('calc'))"],
    ['🎓','Tutoriels',"v21MenuAction(()=>v21OpenTutorialHub())"],
    ['🧰','Mon matériel',"v21MenuAction(()=>v20OpenInventory())"],
    ['📸','Photo / diagnostic',"v21MenuAction(()=>go('diagnostic'))"],
    ['⚙️','Paramètres / profil',"v21MenuAction(()=>openProfileSettings())"]
  ];
  document.body.insertAdjacentHTML('beforeend',`<div class="v21DrawerBack" id="v21Menu" onclick="if(event.target===this)this.remove()"><aside class="v21Drawer"><div class="v21DrawerHead"><div><span>🔨</span><b>Bricoach</b><small>Menu principal</small></div><button onclick="document.querySelector('#v21Menu').remove()">✕</button></div><div class="v21DrawerLinks">${items.map(x=>`<button onclick="${x[2]}"><span>${x[0]}</span><b>${x[1]}</b><em>›</em></button>`).join('')}</div><button class="v21DrawerCoach" onclick="v21MenuAction(()=>go('coach'))">💬 Parler au Coach</button></aside></div>`);
}
try{const v21BaseRender=render;render=function(){v21BaseRender();requestAnimationFrame(v21PatchNavigation)}}catch(_){}

/* ---------- Mon matériel : choix du métier d’abord ---------- */
let v21InventoryCat=null;
const V21_TOOL_CATS=[['Carrelage','🧱'],['Peinture','🎨'],['Sol / parquet','🪵'],['Placo / isolation','🧰'],['Commun','🔧']];
function v21InventoryTop(){return document.querySelector('#v20InventoryModal .v20InventoryModal')?.scrollTop||0}
function v21InventoryRestore(top){requestAnimationFrame(()=>requestAnimationFrame(()=>{const m=document.querySelector('#v20InventoryModal .v20InventoryModal');if(m)m.scrollTop=top}))}
function v21ChooseInventoryCat(cat){v21InventoryCat=cat;v20RenderInventoryBody()}
function v21InventoryChooser(){return `<div class="v21InventoryIntro"><b>Quel matériel veux-tu gérer ?</b><span>Choisis d’abord un métier. Tu pourras revenir ici à tout moment.</span></div><div class="v21InventoryCats">${V21_TOOL_CATS.map(([c,i])=>{const count=Object.entries(V20_TOOL_CATALOG).filter(([,t])=>t.cat===c).length,owned=Object.entries(V20_TOOL_CATALOG).filter(([id,t])=>t.cat===c&&v20Inventory[id]).length;return `<button onclick='v21ChooseInventoryCat(${JSON.stringify(c)})'><span>${i}</span><div><b>${c==='Commun'?'Outils communs':esc(c)}</b><small>${owned}/${count} déjà possédés</small></div><strong>›</strong></button>`}).join('')}</div>`}
function v21InventoryItems(cat){
  const items=Object.entries(V20_TOOL_CATALOG).filter(([,t])=>t.cat===cat);
  return `<div class="v21InventoryCatHead"><button class="btn soft" onclick="v21InventoryCat=null;v20RenderInventoryBody()">← Métiers</button><div><b>${cat==='Commun'?'🔧 Outils communs':`${meta[cat]?.[2]||'🔧'} ${esc(cat)}`}</b><small>Coche uniquement ce que tu possèdes réellement.</small></div></div><div class="v20InventoryGrid">${items.map(([id,t])=>`<label class="v20InventoryItem ${v20Inventory[id]?'owned':''}" data-tool-id="${id}">${v20Visual(t.img,t.emoji,t.name)}<span><b>${esc(t.name)}</b><small>${v20Inventory[id]?'Je le possède déjà':`Achat indicatif ≈ ${t.price} €${t.rentable?` · location ≈ ${t.rent} €/j`:''}`}</small></span><input type="checkbox" ${v20Inventory[id]?'checked':''} onchange="v20SetInventory('${id}',this.checked)"></label>`).join('')}</div>`;
}
function v20RenderInventoryBody(){const el=document.getElementById('v20InventoryBody');if(!el)return;el.innerHTML=v21InventoryCat?v21InventoryItems(v21InventoryCat):v21InventoryChooser()}
function v20SetInventory(id,on){
  v20Inventory[id]=!!on;v20SaveInventory();
  const row=document.querySelector(`#v20InventoryBody [data-tool-id="${id}"]`);if(row){row.classList.toggle('owned',!!on);const small=row.querySelector('small'),t=V20_TOOL_CATALOG[id];if(small)small.textContent=on?'Je le possède déjà':`Achat indicatif ≈ ${t.price} €${t.rentable?` · location ≈ ${t.rent} €/j`:''}`;}
}
function v20OpenInventory(){
  document.querySelector('#v20InventoryModal')?.remove();v21InventoryCat=null;
  document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="v20InventoryModal"><div class="modal v20InventoryModal"><div class="wizardTop"><div><div class="eyebrow">MON MATÉRIEL</div><h2>Mes outils par métier</h2></div><button class="close" onclick="document.querySelector('#v20InventoryModal').remove()">✕</button></div><p class="muted">Les outils déclarés comme possédés sont automatiquement retirés du chiffrage de tous tes chantiers.</p><div id="v20InventoryBody"></div><button class="btn primary full" onclick="document.querySelector('#v20InventoryModal').remove();render()">✓ Enregistrer mon matériel</button></div></div>`);v20RenderInventoryBody();
}

/* ---------- Chiffrage unifié, sans boucle ---------- */
let v21QuoteProjectId=null;
let v21QuoteData=null;
function v21ProjectEntries(p){return (p.locations||[]).flatMap(l=>(l.works||[]).map(w=>({l,w}))) }
function v21PseudoProject(p,l,w){return {id:w.id,title:`${p.title} — ${l.name} — ${w.category}`,category:w.category,room:l.name,area:w.area,range:w.range||'Standard',level:w.level,details:w.details||{},steps:w.steps||[],materials:w.materials||[]}}
function v21QuoteLine(l){const v=typeof v20MatVisual==='function'?v20MatVisual(l.name):{emoji:'📦',img:''};return `<div class="v21ProductLine">${v20Visual(v.img,v.emoji,l.name)}<div class="v21ProductText"><b>${esc(l.name)}</b><small>${esc(l.qty||'')}</small><span>${esc(l.product||'')}</span>${l.verified?'<em class="v21Verified">Prix relevé</em>':'<em class="v21Estimate">À confirmer</em>'}</div><div class="v21ProductPrice"><strong>${formatEuro(l.price||0)}</strong>${l.unit?`<small>${esc(l.unit)}</small>`:''}${l.url?`<a href="${l.url}" target="_blank" rel="noopener">Voir produit / tarif ↗</a>`:''}</div></div>`}
function v21RetailerCard(q,best){if(!q||q.unsupported)return'';return `<article class="v21Retailer ${best?'best':''}">${best?'<span class="v21Best">Meilleur panier vérifié</span>':''}<div class="v21RetailerHead"><div><b>${esc(q.retailer.name)}</b><small>${esc(q.band||'')}</small></div><strong>≈ ${formatEuro(q.total)}</strong></div><div class="v21WebPrice">Prix web de référence · le prix du magasin peut varier</div>${q.lines.map(v21QuoteLine).join('')}${!q.verified?'<div class="v21Unverified">Le produit principal de cette enseigne reste à confirmer et n’est pas utilisé pour désigner le meilleur panier.</div>':''}</article>`}
function v21BuildQuoteData(p,catalog,oldCatalog){
  const entries=v21ProjectEntries(p).map(({l,w})=>{const pseudo=v21PseudoProject(p,l,w),quotes=Object.entries(catalog.retailers).map(([key,r])=>v12QuoteForRetailer(pseudo,key,r,catalog,oldCatalog));const verified=quotes.filter(q=>q.verified&&!q.unsupported).sort((a,b)=>a.total-b.total);return {l,w,pseudo,quotes,bestKey:verified[0]?.key,bestTotal:verified[0]?.total||v14EstimateWork(w)}});
  const retailers={};Object.entries(catalog.retailers).forEach(([key,r])=>{const qs=entries.map(e=>e.quotes.find(q=>q.key===key)).filter(Boolean),supported=qs.filter(q=>!q.unsupported),total=supported.reduce((s,q)=>s+Number(q.total||0),0),verified=supported.length===entries.length&&supported.every(q=>q.verified);retailers[key]={key,name:r.name,total,verified,count:supported.length}});
  return {entries,retailers,materialsBest:entries.reduce((s,e)=>s+e.bestTotal,0)};
}
function v21ToolStatusLabel(st){return st==='owned'?'Je l’ai déjà':st==='rent'?'À louer':st==='skip'?'Inutile':'À acheter'}
function v21QuoteTools(p){const tools=v20ProjectTools(p);return tools.map(t=>{const st=v20ToolStatus(p,t.id),cost=v20ToolCost(p,t);return `<article class="v21QuoteTool ${st}" data-qtool="${t.id}">${v20Visual(t.img,t.emoji,t.name)}<div><b>${esc(t.name)}</b><small>${esc(t.desc)}</small><span>${cost?`≈ ${cost} €`:'0 €'} · ${v21ToolStatusLabel(st)}</span></div><div class="v21QuoteToolActions"><button class="${st==='owned'?'active':''}" onclick="v21SetQuoteTool('${t.id}','owned')">✓ Déjà</button><button class="${st==='buy'?'active':''}" onclick="v21SetQuoteTool('${t.id}','buy')">🛒 Acheter</button>${t.rentable?`<button class="${st==='rent'?'active':''}" onclick="v21SetQuoteTool('${t.id}','rent')">🔁 Louer</button>`:''}<button class="${st==='skip'?'active':''}" onclick="v21SetQuoteTool('${t.id}','skip')">✕ Inutile</button></div></article>`}).join('')}
function v21SetQuoteTool(id,status){const p=projects.find(x=>x.id===v21QuoteProjectId);if(!p)return;v20EnsureState(p)[id]=status;if(status==='owned'){v20Inventory[id]=true;v20SaveInventory()}save();v21RefreshQuoteNumbers();const wrap=document.getElementById('v21QuoteTools');if(wrap)wrap.innerHTML=v21QuoteTools(p)}
function v21RefreshQuoteNumbers(){const p=projects.find(x=>x.id===v21QuoteProjectId);if(!p||!v21QuoteData)return;const tools=v20ToolBudget(p),mat=v21QuoteData.materialsBest||v14ProjectEstimate(p),total=mat+tools;const mt=document.getElementById('v21MatTotal'),tt=document.getElementById('v21ToolTotal'),gt=document.getElementById('v21GrandTotal');if(mt)mt.textContent=`≈ ${Math.round(mat).toLocaleString('fr-FR')} €`;if(tt)tt.textContent=`≈ ${Math.round(tools).toLocaleString('fr-FR')} €`;if(gt)gt.textContent=`≈ ${Math.round(total).toLocaleString('fr-FR')} €`}
function v21RetailerTotals(data){return Object.values(data.retailers).map(r=>`<div class="v21RetailerTotal ${r.verified?'verified':''}"><b>${esc(r.name)}</b><strong>${r.count?`≈ ${Math.round(r.total).toLocaleString('fr-FR')} €`:'Non disponible'}</strong><small>${r.verified?'Tous les postes ont un produit principal vérifié':`${r.count}/${data.entries.length} poste(s) comparable(s)`}</small></div>`).join('')}
async function v21OpenQuote(id){
  const p=projects.find(x=>x.id===id);if(!p)return;try{v14SyncProject(p)}catch(_){};v21QuoteProjectId=id;v21QuoteData=null;
  document.querySelector('#quoteModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="quoteModal"><div class="modal v21QuoteModal"><div class="wizardTop"><div><div class="eyebrow">CHIFFRAGE COMPLET</div><h2>${esc(p.title)}</h2></div><button class="close" onclick="document.querySelector('#quoteModal').remove()">✕</button></div><div id="v21QuoteBody"><div class="storeLoading">Chargement des prix produits et du chantier…</div></div></div></div>`);
  const body=document.getElementById('v21QuoteBody');
  try{
    const catalog=await loadPriceCatalogV12();let oldCatalog=null;try{oldCatalog=await loadPriceCatalog()}catch(_){};const data=v21BuildQuoteData(p,catalog,oldCatalog);v21QuoteData=data;const tools=v20ToolBudget(p),mat=data.materialsBest||v14ProjectEstimate(p);
    body.innerHTML=`<div class="v21QuoteTotals"><div><small>Matériaux — meilleurs prix vérifiés par poste</small><b id="v21MatTotal">≈ ${Math.round(mat).toLocaleString('fr-FR')} €</b></div><div><small>Outils à acheter / louer</small><b id="v21ToolTotal">≈ ${Math.round(tools).toLocaleString('fr-FR')} €</b></div><div class="total"><small>Total indicatif</small><b id="v21GrandTotal">≈ ${Math.round(mat+tools).toLocaleString('fr-FR')} €</b></div></div><div class="v21QuoteNote">Le total matériaux prend le meilleur panier vérifié de chaque poste et peut donc mélanger plusieurs enseignes. Les liens produits et prix utilisés sont visibles ci-dessous.</div><section class="v21Location"><h3>📍 Magasins autour de moi</h3><div class="locationControls"><button class="btn primary" onclick="priceUseMyLocation()">📍 Ma position</button><div class="postcodeBox"><input id="quotePostcode" inputmode="numeric" maxlength="5" placeholder="Code postal"><button class="btn soft" onclick="priceUsePostcode()">Rechercher</button></div></div><div id="priceStoreSummary" class="storeSummary">Tu peux localiser les enseignes, mais les prix affichés restent les prix web relevés et peuvent varier en magasin.</div></section><section><div class="v21SectionHead"><div><h3>Comparaison globale par enseigne</h3><small>Somme des postes comparables dans chaque enseigne.</small></div></div><div class="v21RetailerTotals">${v21RetailerTotals(data)}</div></section><section><div class="v21SectionHead"><div><h3>🧰 Outils pris en compte</h3><small>Tu peux les modifier ici : le total se recalcule immédiatement.</small></div><button class="btn soft" onclick="v20OpenInventory()">Mon matériel</button></div><div id="v21QuoteTools" class="v21QuoteTools">${v21QuoteTools(p)}</div></section><section><div class="v21SectionHead"><div><h3>🛒 Prix et produits par poste</h3><small>Chaque poste affiche Leroy Merlin, Castorama et Brico Dépôt quand une référence est disponible.</small></div></div><div class="v21WorkQuotes">${data.entries.map((e,i)=>`<details ${i===0?'open':''}><summary><span>${meta[e.w.category]?.[2]||'🔧'}</span><div><b>${esc(e.l.name)} · ${esc(e.w.category)}</b><small>${Number(e.w.area).toFixed(1)} m² · ${esc(e.w.range||'Standard')}</small></div><strong>Meilleur ≈ ${Math.round(e.bestTotal).toLocaleString('fr-FR')} €</strong></summary><div class="v21RetailerGrid">${e.quotes.map(q=>v21RetailerCard(q,q.key===e.bestKey)).join('')||'<div class="empty">Aucune référence tarifée pour ce poste.</div>'}</div></details>`).join('')}</div></section><div class="v21QuoteFoot">Prix relevés : ${new Date(catalog.updatedAt).toLocaleDateString('fr-FR')}. Les prix, promotions et stocks peuvent différer selon le magasin ou le dépôt.</div>`;
  }catch(e){console.error(e);body.innerHTML='<div class="diagnostic danger"><b>Catalogue de prix indisponible</b><p>Le chantier reste enregistré. Réessaie dans quelques instants.</p></div>'}
}
try{window.openLocalQuote=v21OpenQuote;openLocalQuote=v21OpenQuote}catch(_){}

/* ---------- Tutoriels interactifs + validation ---------- */
const V21_TILE_VIDEOS={
  pose:{id:'cB01kLork7c',title:'Pose du carrelage sol SDB et douche italienne'},
  leveling:{id:'m61Xr_UKKlo',title:'Pose avec système PAVILIFT / croisillons autonivelants'},
  waterproof:{id:'VeBsmYTyU7k',title:'Réaliser une étanchéité avant carrelage'},
  grout:{id:'tIhM4z5by6Q',title:'Comment faire des joints de carrelage au sol'},
  poseGrout:{id:'_yBILoRVv0U',title:'Pose du carrelage et réalisation des joints'}
};
function v21GuideKey(name=''){const n=name.toLowerCase();if(/étanch|spec|natte/.test(n))return'waterproof';if(/joint/.test(n))return'grout';if(/colle|mortier/.test(n))return'glue';if(/calep|traç/.test(n))return'layout';if(/pose/.test(n))return'pose';if(/support|prépar|protection|ragr/.test(n))return'support';return'generic'}
const V21_TILE_GUIDES={
  support:{title:'Préparer et contrôler le support',why:'La qualité de la pose dépend d’abord du support : propre, cohésif, suffisamment plan et compatible avec le système de pose.',beginner:'Retire poussière, graisse et parties non adhérentes. Passe la main et une règle sur le support. Si tu vois des bosses, creux ou fissures, ne les masque pas avec la colle : traite le support avant la pose.',diy:'Nettoie, contrôle la cohésion et la planéité. Corrige les défauts avant encollage et applique le primaire uniquement si le support et le fabricant le demandent.',confirmed:'Contrôle support, humidité résiduelle si nécessaire, cohésion, planéité et compatibilité primaire/colle. Traite fissures et points singuliers avant calepinage.',expert:'Validation du support selon le système retenu : nature, stabilité, cohésion, planéité, humidité et compatibilités produits. Ne compense pas un défaut structurel avec l’épaisseur de colle.',checks:['Support propre et dépoussiéré','Aucune partie friable','Défauts corrigés avant pose','Primaire compatible si nécessaire'],errors:['Encoller sur poussière','Utiliser la colle pour rattraper de gros défauts','Ignorer une fissure active'],tools:['Aspirateur chantier','Règle / niveau','Grattoir ou spatule','Primaire si nécessaire']},
  waterproof:{title:'Réaliser l’étanchéité',why:'Dans les zones exposées à l’eau, l’étanchéité se traite avant le carrelage : le carreau et le joint ne remplacent pas un système d’étanchéité.',beginner:'Repère toutes les zones mouillées, les angles et passages de tuyaux. Applique le système prévu dans l’ordre du fabricant, avec bandes et manchettes aux points sensibles. Attends le séchage indiqué avant de carreler.',diy:'Traite angles, raccords et traversées avant les surfaces. Respecte primaire, nombre de passes, consommation et temps de séchage du système choisi.',confirmed:'Vérifie continuité, épaisseur/consommation du système, bandes d’angles, manchettes et raccords avec receveur ou évacuation. Respecte strictement la fiche technique.',expert:'Contrôle complet des points singuliers et de la continuité du système. Compatibilité support/étanchéité/colle et temps de recouvrement selon prescriptions fabricant.',checks:['Angles et traversées traités','Système continu sans manque','Temps de séchage respecté','Compatibilité avec la colle'],errors:['Carreler avant séchage','Oublier les manchettes','Penser que le joint suffit à étancher'],tools:['Rouleau / brosse','Spatule','Bandes et manchettes','Système d’étanchéité'],video:'waterproof'},
  layout:{title:'Tracer et faire le calepinage',why:'Le calepinage évite les petites coupes, les décalages visuels et les mauvaises surprises aux portes, angles et équipements.',beginner:'Pose quelques carreaux à sec et mesure les coupes de départ et d’arrivée. Essaie d’obtenir des coupes équilibrées et évite une bande très fine contre un mur visible.',diy:'Détermine tes axes, tes lignes de départ et vérifie les coupes aux points visibles. Contrôle aussi les seuils, niches et alignements avec les équipements.',confirmed:'Calepinage complet des axes, joints, points de fuite et coupes. Anticipe les changements de plan, angles, niches et raccords avec les autres revêtements.',expert:'Optimise trame, axes, joints de fractionnement/périphériques, raccords géométriques et coupes visibles. Valide le départ avant toute gâchée de colle.',checks:['Axes tracés','Coupes visibles équilibrées','Seuils et angles anticipés','Format + largeur de joint pris en compte'],errors:['Démarrer contre un mur sans contrôler','Finir avec une coupe de quelques millimètres','Oublier l’épaisseur du joint'],tools:['Laser ou cordeau','Mètre','Crayon de traçage','Règle']},
  glue:{title:'Préparer la colle',why:'Une colle bien préparée conserve ses performances et donne un encollage régulier.',beginner:'Mesure l’eau comme indiqué sur le sac. Verse la poudre progressivement, mélange au malaxeur, laisse reposer si la fiche le demande puis remélange. Ne rajoute pas d’eau quand la colle commence à tirer.',diy:'Respecte le dosage d’eau, le temps de maturation et la durée pratique d’utilisation. Prépare des quantités adaptées à ta vitesse de pose.',confirmed:'Dosage et malaxage contrôlés, temps de maturation respecté, gâchées adaptées au temps ouvert et aux conditions de chantier.',expert:'Respect strict eau/poudre, maturation, DPU et temps ouvert. Ajuste uniquement l’organisation de pose, jamais la formulation du mortier.',checks:['Dosage fabricant respecté','Mélange homogène','Pas de rajout d’eau après prise','Quantité adaptée au rythme de pose'],errors:['Mettre trop d’eau','Remalaxer une colle déjà prise avec de l’eau','Préparer trop de colle d’un coup'],tools:['Malaxeur','Seau gradué','Eau propre','Peigne adapté']},
  pose:{title:'Poser le carrelage',why:'La pose combine encollage, couverture de colle, alignement, niveau et respect des joints.',beginner:'Étale la colle sur une zone que tu peux couvrir rapidement. Peigne dans le même sens. Pour les formats qui le nécessitent, beurre aussi le dos du carreau. Pose, déplace légèrement le carreau pour écraser les sillons, puis contrôle niveau et alignement. Installe les croisillons autonivelants et serre les cales avec la pince sans forcer excessivement.',diy:'Travaille par zones courtes, contrôle régulièrement couverture et planéité, réalise le double encollage lorsque nécessaire et utilise le système autonivelant sans corriger un mauvais support.',confirmed:'Maîtrise temps ouvert, couverture, direction des sillons, double encollage et alignement. Contrôle régulièrement par dépose d’un carreau témoin. Le nivelant corrige les lèvres, pas le support.',expert:'Gestion du temps ouvert et de la couverture effective, transfert colle/carreau, double encollage selon format/conditions, contrôle des lèvres et géométrie. Les croisillons autonivelants restent un auxiliaire de pose, jamais un rattrapage de planéité.',checks:['Colle encore fraîche au moment de poser','Couverture contrôlée','Joints réguliers','Planéité contrôlée en continu'],errors:['Peigner une trop grande surface','Serrer la pince jusqu’à déplacer le carreau','Utiliser le nivelant pour rattraper un support déformé','Ne jamais vérifier le transfert de colle'],tools:['Peigne à colle','Pince autonivelante','Croisillons autonivelants + cales','Niveau / règle','Maillet','Ventouses si grand format'],video:'leveling',video2:'pose'},
  grout:{title:'Faire les joints et finitions',why:'Le joint finalise la pose et participe à la durabilité de l’ensemble, mais il doit être appliqué au bon moment et nettoyé correctement.',beginner:'Attends le délai prévu par la colle. Retire les éléments du système autonivelant comme indiqué. Mélange le joint, remplis complètement les espaces avec une taloche puis nettoie avec une éponge bien essorée sans creuser les joints.',diy:'Respecte le temps avant jointoiement, remplis en diagonale, retire l’excédent et nettoie en plusieurs passes avec une eau propre.',confirmed:'Préparation et application régulières, contrôle du remplissage, nettoyage au bon moment et traitement adapté des joints périphériques / changements de plan.',expert:'Gestion de la consistance, remplissage et nettoyage sans délaver. Respect des joints périphériques, fractionnements et mastics aux changements de plan selon le système.',checks:['Colle suffisamment sèche','Joints remplis à cœur','Nettoyage sans creuser','Angles / périphéries traités correctement'],errors:['Jointer trop tôt','Trop mouiller l’éponge','Remplir un joint de mouvement avec du joint ciment'],tools:['Taloche à joints','Seau','Éponge','Mélangeur ou spatule'],video:'grout'},
  generic:{title:'Étape du chantier',why:'Cette étape fait partie de l’enchaînement du chantier.',beginner:'Lis la fiche du produit et prépare tout le matériel avant de commencer. Avance progressivement et contrôle ton résultat avant de poursuivre.',diy:'Prépare la zone, respecte les prescriptions fabricant et contrôle l’étape avant l’enchaînement.',confirmed:'Contrôle technique de l’étape, compatibilités et conditions d’exécution.',expert:'Validation des prérequis, compatibilités et points critiques avant enchaînement.',checks:['Prérequis validés','Produits compatibles','Résultat contrôlé'],errors:['Aller trop vite','Ignorer la fiche fabricant'],tools:['Outillage adapté au poste']}
};
function v21LevelDetail(g,level){if(level==='Débutant')return g.beginner;if(level==='Confirmé')return g.confirmed;if(level==='Expert')return g.expert;return g.diy}
function v21VideoBlock(g){const keys=[g.video,g.video2].filter(Boolean);if(!keys.length)return'';return `<div class="v21Videos"><h4>🎥 Voir la démonstration d’Éric Le Carreleur</h4>${keys.map(k=>{const v=V21_TILE_VIDEOS[k];return `<div class="v21Video"><div class="v21VideoFrame"><iframe src="https://www.youtube-nocookie.com/embed/${v.id}" title="${esc(v.title)}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div><b>${esc(v.title)}</b><small>Vidéo YouTube externe — Éric Le Carreleur</small><a href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener">Si la vidéo intégrée ne s’affiche pas, ouvrir sur YouTube ↗</a></div></div>`}).join('')}</div>`}
let v21TutorState=null;
function v21TutorialProgress(w){return w.steps?.length?Math.round(w.steps.filter(s=>s[1]).length/w.steps.length*100):0}
function v21TutorBody(){
  const s=v21TutorState,p=projects.find(x=>x.id===s.projectId),l=p?.locations?.find(x=>x.id===s.locId),w=l?.works?.find(x=>x.id===s.workId);if(!w)return'<div class="empty">Tutoriel introuvable.</div>';const level=typeof v18Level==='function'?v18Level(w.category):'Bricoleur',active=Math.min(s.active,w.steps.length-1),step=w.steps[active],name=step?.[0]||'Étape',g=w.category==='Carrelage'?V21_TILE_GUIDES[v21GuideKey(name)]:V21_TILE_GUIDES.generic,done=!!step?.[1],prog=v21TutorialProgress(w);
  return `<div class="v21TutorHead"><div><span>Niveau ${esc(level)} · ${esc(l.name)}</span><b>${esc(w.category)}</b></div><strong>${prog}% terminé</strong></div><div class="progress"><span style="width:${prog}%"></span></div><div class="v21TutorList">${(w.steps||[]).map((x,i)=>`<button class="${i===active?'active':''} ${x[1]?'done':''}" onclick="v21TutorSelect(${i})"><span>${x[1]?'✓':i+1}</span><div><b>${esc(x[0])}</b><small>${x[1]?'Effectuée':'Cliquer pour le détail'}</small></div><em>›</em></button>`).join('')}</div><article class="v21TutorDetail"><div class="v21TutorDetailTitle"><span>${active+1}</span><div><h3>${esc(g.title||name)}</h3><p>${esc(g.why||'')}</p></div></div><div class="v21LevelBox"><b>${level==='Débutant'?'🌱':level==='Expert'?'🏆':level==='Confirmé'?'🛠️':'🔧'} Explication niveau ${esc(level)}</b><p>${esc(v21LevelDetail(g,level))}</p></div><div class="v21TutorCols"><div><h4>✓ À contrôler</h4>${(g.checks||[]).map(x=>`<p>✓ ${esc(x)}</p>`).join('')}</div><div><h4>⚠️ Erreurs à éviter</h4>${(g.errors||[]).map(x=>`<p>• ${esc(x)}</p>`).join('')}</div></div><div class="v21TutorTools"><h4>🧰 Outils / produits utiles</h4><div>${(g.tools||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div></div>${w.category==='Carrelage'?v21VideoBlock(g):''}<button class="btn ${done?'soft':'primary'} full v21Validate" onclick="v21TutorToggleDone()">${done?'↩ Marquer comme non terminée':'✓ J’ai effectué cette étape'}</button></article>`;
}
function v21TutorSelect(i){if(!v21TutorState)return;const sc=document.querySelector('#v21TutorModal .v21TutorModal'),top=sc?.scrollTop||0;v21TutorState.active=i;const body=document.getElementById('v21TutorBody');if(body)body.innerHTML=v21TutorBody();requestAnimationFrame(()=>{const d=document.querySelector('#v21TutorModal .v21TutorDetail');d?.scrollIntoView({behavior:'smooth',block:'start'});});}
function v21TutorToggleDone(){const s=v21TutorState,p=projects.find(x=>x.id===s.projectId),l=p?.locations?.find(x=>x.id===s.locId),w=l?.works?.find(x=>x.id===s.workId);if(!w?.steps?.[s.active])return;w.steps[s.active][1]=w.steps[s.active][1]?0:1;try{v14SyncProject(p)}catch(_){};save();const body=document.getElementById('v21TutorBody');if(body)body.innerHTML=v21TutorBody()}
function openAdaptiveTutorial(projectId,locId,workId){const p=projects.find(x=>x.id===projectId),l=p?.locations?.find(x=>x.id===locId),w=l?.works?.find(x=>x.id===workId);if(!w)return;v21TutorState={projectId,locId,workId,active:0};document.querySelector('#v21TutorModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="v21TutorModal"><div class="modal v21TutorModal"><div class="wizardTop"><div><div class="eyebrow">TUTORIEL INTERACTIF</div><h2>${meta[w.category]?.[2]||'🔧'} ${esc(w.category)} · ${esc(l.name)}</h2></div><button class="close" onclick="document.querySelector('#v21TutorModal').remove();render()">✕</button></div><div id="v21TutorBody">${v21TutorBody()}</div></div></div>`)}
function v21OpenTutorialHub(){
  document.querySelector('#v21TutorHub')?.remove();const rows=[];(projects||[]).forEach(p=>{try{v14SyncProject(p)}catch(_){};(p.locations||[]).forEach(l=>(l.works||[]).forEach(w=>rows.push({p,l,w})))});
  document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="v21TutorHub"><div class="modal v21TutorHub"><div class="wizardTop"><div><div class="eyebrow">TUTORIELS</div><h2>Mes tutoriels chantier</h2></div><button class="close" onclick="document.querySelector('#v21TutorHub').remove()">✕</button></div>${rows.length?`<div class="v21TutorHubList">${rows.map(x=>`<button onclick="document.querySelector('#v21TutorHub').remove();openAdaptiveTutorial(${x.p.id},${x.l.id},${x.w.id})"><span>${meta[x.w.category]?.[2]||'🔧'}</span><div><b>${esc(x.w.category)} · ${esc(x.l.name)}</b><small>${esc(x.p.title)} · ${v21TutorialProgress(x.w)}% effectué</small></div><strong>Ouvrir →</strong></button>`).join('')}</div>`:`<div class="empty"><b>Aucun chantier enregistré.</b><p>Crée un projet pour pouvoir valider l’avancement des tutoriels étape par étape.</p></div>`}</div></div>`);
}

try{render()}catch(_){}
