/* Bricoach V25 — tutoriels complets Peinture / Placo / Sol-Parquet-Vinyle + vidéothèques */

const V25_CHANNELS={
  'Peinture':{name:'Docteur Peinture',sub:'≈ 239 k abonnés',url:'https://www.youtube.com/@docteurpeinture'},
  'Placo / isolation':{name:'TAKA YAKA',sub:'≈ 232 k abonnés',url:'https://www.youtube.com/@takayaka'},
  'Sol / parquet':{name:'Leroy Merlin Campus',sub:'≈ 366 k abonnés',url:'https://www.youtube.com/@leroymerlin'}
};
const V25_VIDEOS={
  'Peinture':[
    {id:'eNqnXIUb_Zc',title:'Par où commencer quand on débute en peinture ?',cat:'Bases',tags:['protéger','début','outils','préparer']},
    {id:'JC9SGrXXfpw',title:'20 astuces à connaître avant de peindre',cat:'Préparation',tags:['préparer','protéger','support','erreurs']},
    {id:'xzGHu5FKTzk',title:'Enduire un mur pour débutant / lisser un mur',cat:'Préparation',tags:['reboucher','poncer','enduit','support']},
    {id:'QxdKlpA4lIw',title:'Peindre un mur blanc comme un pro',cat:'Mur',tags:['mur','première couche','deuxième couche','rouleau','réchampir']},
    {id:'vZeh4TUQEP0',title:'Peindre un mur en couleur comme un pro',cat:'Mur',tags:['mur','couleur','réchampir','rouleau']},
    {id:'DH2-jEEGnRg',title:'Peindre sans laisser de traces',cat:'Finition',tags:['traces','première couche','deuxième couche','finition','rouleau']},
    {id:'hUl-biKL-IQ',title:'Peindre un plafond de salle de bain',cat:'Plafond',tags:['plafond','humide','salle de bain','finition']}
  ],
  'Placo / isolation':[
    {id:'Qn9J9ODcEvs',title:'Doublage : comparer les systèmes d’ossature',cat:'Ossature',tags:['rails','montants','doublage','ossature','tracer']},
    {id:'eK9VELU4lBI',title:'Pose professionnelle des bandes à joint',cat:'Bandes',tags:['bandes','joint','enduit']},
    {id:'oqKjjV6LsWQ',title:'Une bande placo bien faite : comment le savoir ?',cat:'Contrôle',tags:['bandes','contrôle','joint','finition']},
    {id:'2oqAtjoxeQ8',title:'Enduits à joints : collage, charge et finition',cat:'Enduit',tags:['enduit','collage','charge','finition','bandes']}
  ],
  'Sol / parquet':[
    {id:'EZc3KgZhyVo',title:'Poser facilement un sol stratifié à clipser',cat:'Stratifié',tags:['stratifié','clipser','pose','premières rangées']},
    {id:'_K3keWrPxKg',title:'Poser un parquet flottant à clic angulaire',cat:'Parquet',tags:['parquet','flottant','clic','pose','dilatation']},
    {id:'l1kFGTNf6yw',title:'Poser des dalles et lames vinyles à clipser',cat:'Vinyle',tags:['vinyle','pvc','clipser','pose','coupes']},
    {id:'7JHeZ_09jQs',title:'Déposer un ancien parquet flottant',cat:'Dépose',tags:['dépose','ancien','support']},
    {id:'VmXaLEJZF5g',title:'Changer une lame de parquet stratifié',cat:'Réparation',tags:['réparer','lame','stratifié','coupes']},
    {id:'haXJFnDqkG0',title:'Poser des plinthes à clipser',cat:'Finitions',tags:['plinthes','finition']}
  ]
};

const V25_GUIDES={
  'Peinture':{
    protect:{title:'Protéger la pièce',why:'Une protection bien pensée fait gagner du temps et évite les reprises après peinture.',beginner:'Vide au maximum la pièce. Protège le sol avec une bâche adaptée, masque soigneusement plinthes, prises et menuiseries, puis démonte ce qui peut l’être.',diy:'Protège les zones sensibles, démonte les appareillages si possible et prépare un chemin de circulation propre.',confirmed:'Protection sélective, démontage des éléments gênants et organisation du chantier pour limiter poussière et reprises.',expert:'Optimise le masquage, les zones de circulation et l’ordre des travaux pour réduire les reprises et les temps morts.',checks:['Sol protégé sans zone ouverte','Prises/interrupteurs sécurisés','Plinthes et menuiseries masquées','Zone de mélange protégée'],errors:['Masquer sur un support poussiéreux','Utiliser une bâche glissante','Laisser les protections trop longtemps'],tools:['Bâches','Ruban de masquage','Cutter','Tournevis']},
    clean:{title:'Nettoyer et préparer le support',why:'La peinture adhère au support, pas à la poussière ni au gras.',beginner:'Dépoussière, lessive si nécessaire, rince et laisse sécher. Gratte tout ce qui n’adhère pas avant de continuer.',diy:'Contrôle propreté, cohésion et anciennes peintures. Matifie les surfaces trop fermées avant reprise.',confirmed:'Qualification du support, dégraissage, égrenage et traitement des fonds fragiles avant impression.',expert:'Contrôle adhérence/cohésion, compatibilité des anciens fonds et choix du système de préparation adapté.',checks:['Support sec','Pas de poussière ni graisse','Ancienne peinture adhérente','Défauts repérés'],errors:['Peindre sur gras','Poncer sans dépoussiérer','Lessiver puis peindre avant séchage'],tools:['Aspirateur','Éponge','Lessive adaptée','Grattoir']},
    repair:{title:'Reboucher, enduire et poncer',why:'Une peinture ne masque pas les défauts : elle les révèle souvent davantage.',beginner:'Ouvre les fissures non actives, rebouche les trous, laisse sécher, puis ponce progressivement jusqu’à obtenir une surface lisse.',diy:'Rebouchage local puis enduit de lissage si nécessaire. Égrène entre les passes et contrôle à lumière rasante.',confirmed:'Choisis reboucheur, garnissant ou lissage selon le défaut. Contrôle planéité et raccords avant impression.',expert:'Travaille les passes et granulométries selon la finition visée, contrôle à lumière rasante et traite les défauts structurels avant décoration.',checks:['Trous comblés','Pas d’arêtes d’enduit','Surface dépoussiérée','Raccords invisibles au toucher'],errors:['Poncer trop tôt','Faire une couche trop épaisse','Noyer une fissure active dans l’enduit'],tools:['Couteaux à enduire','Enduit adapté','Abrasifs','Lumière rasante']},
    primer:{title:'Appliquer la sous-couche si nécessaire',why:'L’impression uniformise l’absorption et sécurise l’adhérence de la finition.',beginner:'Choisis une sous-couche adaptée au support, mélange-la, applique sans surcharge et respecte le séchage indiqué.',diy:'Utilise l’impression uniquement lorsqu’elle apporte une vraie fonction : blocage, adhérence ou uniformisation.',confirmed:'Sélectionne l’impression selon porosité, ancien fond et finition. Respecte rendement et recouvrabilité.',expert:'Valide le couple support/impression/finition et évite les impressions universelles lorsque le fond exige un système spécifique.',checks:['Produit compatible','Rendement respecté','Pas de manque','Séchage complet'],errors:['Sous-couche inutile sur mauvais fond','Surcharger','Recouvrir trop tôt'],tools:['Rouleau','Brosse à réchampir','Bac/grille','Sous-couche']},
    cutin:{title:'Faire les réchampis et les angles',why:'Les bordures propres conditionnent la qualité visuelle finale.',beginner:'Charge peu la brosse, approche progressivement de l’angle et avance par petites zones avant de passer le rouleau.',diy:'Réalise le réchampi au fur et à mesure du rouleau pour conserver un bord humide.',confirmed:'Gestion du bord humide, largeur régulière de réchampi et raccord sans surépaisseur.',expert:'Réchampis rapides et réguliers, sans corde ni surcharge, raccordés immédiatement au rouleau.',checks:['Ligne nette','Pas de surcharge','Raccord frais avec rouleau','Angles couverts'],errors:['Faire tous les angles puis attendre','Trop charger la brosse','Créer une bande épaisse visible'],tools:['Brosse à réchampir','Petit rouleau','Pot à peinture']},
    coat1:{title:'Appliquer la première couche',why:'La première couche doit déposer la bonne quantité de produit sans chercher à “tirer” excessivement la peinture.',beginner:'Travaille par zones, charge correctement le rouleau, répartis puis lisse sans appuyer fort. Garde toujours un bord humide.',diy:'Dépose suffisamment de matière, travaille par lés réguliers et termine chaque zone dans le même sens.',confirmed:'Maîtrise charge, largeur de passe, temps ouvert et raccords pour éviter reprises et embus.',expert:'Rendement, mouillage du support, cadence et température/hygrométrie pilotés pour maintenir un film uniforme.',checks:['Rouleau chargé régulièrement','Bord humide conservé','Pas de manque','Pas de coulure'],errors:['Appuyer pour “économiser” la peinture','Revenir sur une zone qui tire','Travailler dans une pièce trop chaude'],tools:['Rouleau adapté','Perche','Grille','Peinture']},
    coat2:{title:'Appliquer la deuxième couche sans traces',why:'La seconde couche uniformise teinte, opacité et aspect.',beginner:'Attends le séchage complet. Corrige les petits défauts, dépoussière, puis applique comme la première couche en terminant tous les passages dans le même sens.',diy:'Égrène si nécessaire, reprends les défauts puis travaille avec une charge régulière sans repasser sur la peinture qui commence à tirer.',confirmed:'Contrôle reprises, tension du film et éclairage rasant pendant l’application.',expert:'Gestion fine du temps ouvert, de la température, de la charge et de l’orientation du dernier passage selon lumière et finition.',checks:['Séchage précédent respecté','Défauts corrigés','Opacité homogène','Aspect uniforme à lumière rasante'],errors:['Redoubler trop tôt','Repasser à sec','Changer de sens de finition sans raison'],tools:['Rouleau neuf ou propre','Perche','Brosse','Éclairage rasant']},
    finish:{title:'Retirer les protections et contrôler',why:'La dernière étape évite d’abîmer un travail réussi au moment du nettoyage.',beginner:'Retire les rubans avant qu’ils ne deviennent difficiles à décoller, coupe au cutter si la peinture a formé un film, puis contrôle la pièce avec différents éclairages.',diy:'Dépose les protections proprement, fais les petites retouches et nettoie les outils immédiatement.',confirmed:'Contrôle lumière rasante, reprises locales et joints acryliques éventuels après séchage adapté.',expert:'Contrôle final teinte/aspect/raccords, retouches localisées sans créer de différences de tension.',checks:['Rubans retirés proprement','Pas de coulure','Angles nets','Outils nettoyés'],errors:['Arracher une peinture fraîche avec le ruban','Retoucher une grande zone déjà sèche','Nettoyer agressivement trop tôt'],tools:['Cutter','Petit pinceau','Éclairage','Chiffons']}
  },
  'Placo / isolation':{
    trace:{title:'Tracer l’implantation',why:'Une ossature mal implantée se retrouve dans toutes les finitions.',beginner:'Trace l’axe de la cloison au sol, reporte-le au plafond au laser ou au fil à plomb et repère portes, réseaux et renforts.',diy:'Contrôle axes, aplomb et équerrage avant de fixer les rails.',confirmed:'Implantation complète avec réservations, réseaux et points singuliers avant ossature.',expert:'Valide géométrie, interfaces, performances acoustiques/feu et renforts avant tout percement.',checks:['Axes cohérents sol/plafond','Équerrage vérifié','Ouvertures reportées','Réseaux anticipés'],errors:['Tracer seulement au sol','Oublier l’épaisseur finie','Ne pas prévoir les renforts'],tools:['Laser','Cordeau','Mètre','Crayon']},
    frame:{title:'Poser rails et montants',why:'L’ossature donne rigidité, planéité et résistance à l’ouvrage.',beginner:'Fixe les rails selon le support, coupe les montants à la bonne longueur, positionne-les dans le même sens et respecte l’entraxe prévu.',diy:'Contrôle entraxes, appuis, sertissage et aplomb. Double les montants aux points nécessaires.',confirmed:'Dimensionne ossature, entraxes et renforts selon hauteur, type de plaque et charges.',expert:'Contrôle système complet fabricant/DTU, désolidarisation, contraintes acoustiques et charges rapportées.',checks:['Rails fixés au bon pas','Montants d’aplomb','Entraxes réguliers','Renforts prévus'],errors:['Mélanger des systèmes incompatibles','Entraxe aléatoire','Oublier les bandes résilientes si nécessaires'],tools:['Cisaille','Pince à sertir','Visseuse','Laser']},
    insulation:{title:'Mettre l’isolation et les réseaux',why:'Une cloison refermée devient difficile à corriger.',beginner:'Passe les gaines sans les pincer, pose l’isolant sans trous ni compression excessive puis prends des photos avant fermeture.',diy:'Traite continuité de l’isolant, passages de gaines et boîtiers sans créer de ponts inutiles.',confirmed:'Soigne continuité thermo-acoustique et traversées, avec fourreaux et étanchéité adaptée.',expert:'Contrôle densité, continuité, interfaces et performances du complexe avant fermeture.',checks:['Isolant continu','Gaines non pincées','Boîtiers repérés','Photos avant fermeture'],errors:['Comprimer l’isolant','Laisser de grands vides','Couper des montants pour passer les réseaux'],tools:['Cutter isolant','Gants/masque','Passe-fil','Appareil photo']},
    boards:{title:'Poser les plaques',why:'Le calepinage des plaques conditionne la rigidité et la qualité des joints.',beginner:'Mesure, coupe au cutter, casse la plaque proprement et présente-la en laissant les jeux nécessaires. Décale les joints entre rangées si le système le demande.',diy:'Optimise les coupes, évite les joints dans les angles d’ouvertures et appuie toujours les bords sur l’ossature prévue.',confirmed:'Calepinage, jeux, bords, découpes et points singuliers réalisés selon le système.',expert:'Pose conforme au système complet avec traitement anticipé des joints, bords coupés et interfaces.',checks:['Bords supportés','Découpes propres','Pas de joint fragile aux angles','Jeux respectés'],errors:['Visser un bord dans le vide','Créer une croix de joints','Casser le carton'],tools:['Cutter','Rabot à placo','Lève-plaque si besoin','Visseuse']},
    screws:{title:'Contrôler le vissage',why:'Une vis trop haute gêne l’enduit ; trop profonde, elle détruit le carton et la tenue.',beginner:'Enfonce la tête juste sous le carton sans le déchirer. Passe la spatule : elle ne doit pas accrocher.',diy:'Contrôle profondeur, pas de vissage et fixation dans chaque profil utile.',confirmed:'Vissage régulier, retraitement des vis ratées et contrôle des bords avant bandes.',expert:'Contrôle systématique du vissage, des bords amincis et des défauts de pose avant intervention du jointeur.',checks:['Têtes légèrement noyées','Carton intact','Aucune vis qui dépasse','Vis ratées doublées/corrigées'],errors:['Déchirer le carton','Visser trop près du bord','Laisser une vis saillante'],tools:['Visseuse avec butée','Spatule','Vis adaptées']},
    tape:{title:'Poser les bandes à joint',why:'La bande papier correctement noyée limite fortement les risques de fissuration.',beginner:'Garnis le joint, pose la bande dans l’enduit frais puis serre-la avec le couteau sans enlever tout l’enduit dessous. Traite les angles avec la bande pliée.',diy:'Adapte la consistance de l’enduit au collage et chasse l’air sans assécher le joint.',confirmed:'Collage homogène, serrage maîtrisé, angles et bords coupés préparés avant charge.',expert:'Gestion épaisseur, largeur de passes et préparation des joints pour minimiser la bosse finale et le ponçage.',checks:['Pas de bulle','Bande centrée','Enduit sous toute la bande','Angles nets'],errors:['Bande grillagée utilisée par défaut','Serrer jusqu’à enlever tout l’enduit','Coller sur poussière'],tools:['Couteaux à enduire','Bande papier','Enduit à joint','Auge']},
    coat:{title:'Charger et finir les joints',why:'Les passes successives doivent élargir progressivement le joint sans créer de bosse.',beginner:'Après séchage, gratte les bavures, applique une passe plus large puis une finition encore plus large. Laisse sécher entre chaque passe.',diy:'Élargis les passes, garde les bords fins et évite de surcharger le centre.',confirmed:'Profil du joint contrôlé à la règle/lumière rasante, finition adaptée à la peinture prévue.',expert:'Optimise charge, feathering et niveau de finition selon éclairage et aspect final visé.',checks:['Passes sèches entre couches','Bords tirés finement','Pas de surépaisseur centrale','Angles propres'],errors:['Poncer pour corriger une grosse bosse','Charger trop épais','Recouvrir un enduit encore humide'],tools:['Couteaux 15/25/35 cm','Platoir/lame','Enduit de finition']},
    sand:{title:'Poncer et préparer la finition',why:'Le ponçage doit supprimer les défauts sans creuser les joints ni attaquer le carton.',beginner:'Utilise un abrasif fin, une lumière rasante et aspire souvent. Arrête dès que la surface devient régulière au toucher.',diy:'Ponçage localisé, dépoussiérage complet puis contrôle avant impression.',confirmed:'Contrôle lumière rasante et préparation Q3/Q4 selon finition attendue.',expert:'Ponçage minimal, correction localisée et validation de la qualité de surface avant impression.',checks:['Pas de rayure profonde','Carton intact','Surface dépoussiérée','Défauts contrôlés à lumière rasante'],errors:['Poncer trop fort','Creuser la bande','Peindre sur poussière'],tools:['Cale/ponceuse girafe','Aspirateur','Éclairage rasant','Masque']}
  },
  'Sol / parquet':{
    support:{title:'Contrôler et préparer le support',why:'Planéité, sécheresse et propreté déterminent la tenue du sol.',beginner:'Retire les anciens revêtements instables, aspire, contrôle la planéité avec une règle et ragrée si nécessaire.',diy:'Contrôle planéité, humidité, cohésion et compatibilité avec la sous-couche ou la colle.',confirmed:'Mesure humidité si nécessaire, traite les défauts et vérifie les tolérances du fabricant.',expert:'Qualification complète du support et choix du système de préparation/pare-vapeur selon ouvrage.',checks:['Support sec','Planéité conforme','Pas de partie mobile','Sol propre'],errors:['Poser sur bosse','Enfermer de l’humidité','Compter sur la sous-couche pour rattraper de gros défauts'],tools:['Règle de maçon','Niveau','Aspirateur','Humidimètre si besoin']},
    acclimate:{title:'Acclimater et trier les lames',why:'Le bois et certains stratifiés doivent atteindre l’équilibre hygrométrique de la pièce.',beginner:'Stocke les paquets à plat dans la pièce pendant la durée indiquée par le fabricant. Mélange les lames de plusieurs paquets au moment de la pose.',diy:'Respecte température/hygrométrie et contrôle les teintes avant pose.',confirmed:'Acclimatation, humidité ambiante et mélange des lots vérifiés avant ouverture massive des paquets.',expert:'Contrôle conditions chantier et compatibilité produit/support/chauffage au sol avant pose.',checks:['Paquets stockés à plat','Température stable','Lots mélangés','Lames défectueuses écartées'],errors:['Poser immédiatement après livraison froide','Stocker debout','Ne pas mélanger les boîtes'],tools:['Thermo-hygromètre si nécessaire']},
    underlay:{title:'Poser pare-vapeur et sous-couche',why:'La sous-couche améliore acoustique et confort ; le pare-vapeur protège des remontées d’humidité quand il est requis.',beginner:'Déroule sans plis, joins les lés bord à bord et scotche les raccords selon la notice. Ne superpose pas les sous-couches sauf indication.',diy:'Choisis la sous-couche selon support, chauffage au sol et exigences acoustiques.',confirmed:'Vérifie résistance thermique, pare-vapeur et compatibilité système.',expert:'Dimensionne le complexe sous-couche/pare-vapeur selon contraintes hygrothermiques et performance demandée.',checks:['Pas de plis','Raccords fermés','Produit compatible chauffage au sol','Pare-vapeur prévu si nécessaire'],errors:['Doubler les sous-couches','Créer des bosses aux raccords','Utiliser une sous-couche incompatible'],tools:['Cutter','Ruban adapté','Sous-couche','Pare-vapeur']},
    layout:{title:'Choisir le sens et faire le calepinage',why:'Le sens de pose et la largeur du dernier rang influencent fortement le rendu.',beginner:'Mesure la largeur de la pièce, calcule le dernier rang et ajuste le premier si le dernier devient trop étroit. Choisis le sens selon la lumière et la géométrie.',diy:'Anticipe seuils, portes, coupes et continuité entre pièces.',confirmed:'Calepinage complet avec joints de fractionnement et raccords aux autres sols.',expert:'Valide orientation, trame, seuils et fractionnements selon dimensions et prescriptions fabricant.',checks:['Dernier rang acceptable','Sens choisi avant pose','Seuils anticipés','Jeux périphériques prévus'],errors:['Commencer sans calcul','Finir avec une lame trop étroite','Oublier les cadres de porte'],tools:['Mètre','Équerre','Crayon','Règle']},
    pose:{title:'Poser les premières rangées',why:'Une première rangée droite conditionne tout le reste du sol.',beginner:'Pose les cales périphériques, assemble les lames sans forcer et contrôle l’alignement à chaque rang. Utilise la chute du rang précédent si elle respecte la longueur minimale.',diy:'Maintiens les décalages de joints, contrôle le clipsage et n’abîme pas les languettes.',confirmed:'Pose fluide avec décalage maîtrisé et contrôle des verrouillages.',expert:'Gestion des tolérances, trame et raccords sans contrainte parasite dans les assemblages.',checks:['Première rangée droite','Clips complètement fermés','Décalage des joints respecté','Aucun bord éclaté'],errors:['Frapper directement la lame','Forcer un clip mal engagé','Aligner les joints bout à bout'],tools:['Kit de pose','Maillet','Cale martyre','Tire-lame']},
    expansion:{title:'Respecter les jeux périphériques',why:'Les revêtements flottants doivent pouvoir se dilater sans pousser les murs.',beginner:'Conserve le jeu indiqué par le fabricant tout autour, y compris aux tuyaux, huisseries et poteaux.',diy:'Maintiens un jeu continu et ne bloque jamais le sol avec silicone, vis ou meuble fixé à travers.',confirmed:'Traite seuils et grandes surfaces avec fractionnements adaptés.',expert:'Jeux périphériques et fractionnements dimensionnés selon produit, surface et géométrie.',checks:['Jeu continu','Aucun point bloqué','Seuils traités','Cales retirées en fin de pose'],errors:['Plaquer contre le mur','Visser une plinthe dans le sol','Remplir le jeu avec un produit rigide'],tools:['Cales de dilatation','Mètre']},
    cuts:{title:'Réaliser les coupes et passages',why:'Des coupes propres rendent les finitions faciles et évitent de fragiliser les lames.',beginner:'Trace sur la bonne face selon l’outil, laisse le jeu de dilatation et teste la pièce avant clipsage définitif.',diy:'Utilise gabarits pour huisseries/tuyaux et garde des coupes suffisamment larges pour rester solides.',confirmed:'Découpes précises, sous-coupe des huisseries et raccords invisibles sous finitions.',expert:'Optimisation des coupes, seuils et raccords complexes en conservant les jeux fonctionnels.',checks:['Jeu conservé','Coupe nette','Pas de lame fragilisée','Raccord caché par finition'],errors:['Couper trop juste','Forcer une lame découpée','Oublier le jeu autour des tuyaux'],tools:['Scie sauteuse','Cutter pour vinyle','Équerre','Gabarit']},
    finish:{title:'Poser plinthes, seuils et finitions',why:'Les finitions masquent les jeux sans bloquer le revêtement.',beginner:'Retire les cales, fixe les plinthes au mur et pose les barres de seuil sans visser à travers le sol flottant.',diy:'Traite angles de plinthes, seuils et raccords avec les accessoires adaptés.',confirmed:'Finitions continues sans blocage du sol et joints propres aux points singuliers.',expert:'Contrôle final dilatation, seuils, acoustique et esthétique avant remise en service.',checks:['Cales retirées','Plinthes fixées au mur','Seuils stables','Sol libre de bouger'],errors:['Fixer la plinthe dans le parquet','Boucher le jeu avec mortier','Coincer le sol sous une huisserie'],tools:['Scie à onglet','Colle/clip plinthe','Barres de seuil','Mètre']}
  }
};

function v25GuideKey(cat,name=''){
  const n=name.toLowerCase();
  if(cat==='Peinture'){
    if(/protéger/.test(n))return'protect';if(/lessiv|dépous|nettoy/.test(n))return'clean';if(/rebouch|ponc/.test(n))return'repair';if(/sous-couche/.test(n))return'primer';if(/angle|réchamp/.test(n))return'cutin';if(/première/.test(n))return'coat1';if(/deuxième/.test(n))return'coat2';return'finish';
  }
  if(cat==='Placo / isolation'){
    if(/tracer/.test(n))return'trace';if(/rail|montant/.test(n))return'frame';if(/isol/.test(n))return'insulation';if(/poser les plaques/.test(n))return'boards';if(/vissage/.test(n))return'screws';if(/bande/.test(n))return'tape';if(/enduire/.test(n))return'coat';return'sand';
  }
  if(cat==='Sol / parquet'){
    if(/support/.test(n))return'support';if(/acclimat/.test(n))return'acclimate';if(/sous-couche/.test(n))return'underlay';if(/tracer|sens de pose/.test(n))return'layout';if(/premières rangées/.test(n))return'pose';if(/jeu périph/.test(n))return'expansion';if(/coupe|seuil/.test(n))return'cuts';return'finish';
  }
  return null;
}
const v25BaseGuide=typeof v22Guide==='function'?v22Guide:null;
v22Guide=function(cat,name,level){const k=v25GuideKey(cat,name);if(k&&V25_GUIDES[cat]?.[k])return V25_GUIDES[cat][k];return v25BaseGuide?v25BaseGuide(cat,name,level):v22GenericGuide(cat,name,level)};

function v25VideoThumb(v){return `https://i.ytimg.com/vi/${v.id}/hqdefault.jpg`}
function v25VideoCard(cat,v){const ch=V25_CHANNELS[cat];return `<button class="v25VideoCard" onclick='v25OpenVideo(${JSON.stringify(cat)},${JSON.stringify(v.id)})'><span class="v25VideoImg"><img src="${v25VideoThumb(v)}" alt="${esc(v.title)}" loading="lazy"><i>▶</i></span><span class="v25VideoText"><em>${esc(v.cat)}</em><b>${esc(v.title)}</b><small>${esc(ch?.name||'YouTube')}</small></span></button>`}
function v25FindVideo(cat,id){return (V25_VIDEOS[cat]||[]).find(v=>v.id===id)}
function v25OpenVideo(cat,id){const v=v25FindVideo(cat,id),ch=V25_CHANNELS[cat];if(!v)return;document.querySelector('#v25VideoModal')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="v25VideoModal"><div class="modal v24VideoModal"><div class="wizardTop"><div><div class="eyebrow">DÉMONSTRATION VIDÉO</div><h2>${esc(v.title)}</h2></div><button class="close" onclick="document.querySelector('#v25VideoModal').remove()">✕</button></div><div class="v24Player"><iframe src="https://www.youtube-nocookie.com/embed/${v.id}?rel=0" title="${esc(v.title)}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="v24VideoMeta"><div><b>🎥 ${esc(ch?.name||'YouTube')}</b><small>${esc(v.cat)} · ${esc(ch?.sub||'')}</small></div><a class="btn soft" target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=${v.id}">Ouvrir sur YouTube ↗</a></div><div class="v24EmbedNote">La vidéo reste hébergée chez YouTube. Si la lecture intégrée est bloquée, utilise le lien YouTube.</div></div></div>`)}
function v25OpenVideoLibrary(cat){const vids=V25_VIDEOS[cat]||[],ch=V25_CHANNELS[cat];document.querySelector('#v25VideoLibrary')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modalBack" id="v25VideoLibrary"><div class="modal v24VideoLibrary"><div class="wizardTop"><div><div class="eyebrow">VIDÉOTHÈQUE ${esc(cat.toUpperCase())}</div><h2>🎬 ${esc(ch?.name||cat)}</h2></div><button class="close" onclick="document.querySelector('#v25VideoLibrary').remove()">✕</button></div><div class="v25ExpertBox"><b>${esc(ch?.name||'')}</b><span>${esc(ch?.sub||'')} · source vidéo principale sélectionnée par Bricoach pour ce métier.</span></div><div class="v24VideoGrid">${vids.map(v=>v25VideoCard(cat,v)).join('')}</div><a class="btn soft full v24ChannelLink" target="_blank" rel="noopener" href="${ch?.url||'#'}">Voir toute la chaîne ${esc(ch?.name||'')} ↗</a></div></div>`)}
function v25RelatedVideos(cat,step=''){const vids=V25_VIDEOS[cat]||[],s=String(step).toLowerCase();let out=vids.filter(v=>v.tags?.some(t=>s.includes(t)||t.includes(s)));if(cat==='Peinture'){
  if(/protéger|lessiv|dépous/.test(s))out=vids.filter(v=>['eNqnXIUb_Zc','JC9SGrXXfpw'].includes(v.id));
  else if(/rebouch|ponc/.test(s))out=vids.filter(v=>v.id==='xzGHu5FKTzk');
  else if(/couche|réchamp|angle/.test(s))out=vids.filter(v=>['QxdKlpA4lIw','DH2-jEEGnRg'].includes(v.id));
  else if(/plafond/.test(s))out=vids.filter(v=>v.id==='hUl-biKL-IQ');
}else if(cat==='Placo / isolation'){
  if(/rail|montant|tracer|isol/.test(s))out=vids.filter(v=>v.id==='Qn9J9ODcEvs');
  else if(/bande/.test(s))out=vids.filter(v=>['eK9VELU4lBI','oqKjjV6LsWQ'].includes(v.id));
  else if(/enduit|ponc|finition/.test(s))out=vids.filter(v=>['2oqAtjoxeQ8','oqKjjV6LsWQ'].includes(v.id));
}else if(cat==='Sol / parquet'){
  if(/support/.test(s))out=vids.filter(v=>v.id==='7JHeZ_09jQs');
  else if(/pose|rang|dilat|sous-couche|sens/.test(s))out=vids.filter(v=>['EZc3KgZhyVo','_K3keWrPxKg'].includes(v.id));
  else if(/coupe/.test(s))out=vids.filter(v=>['l1kFGTNf6yw','VmXaLEJZF5g'].includes(v.id));
  else if(/plinthe|finition/.test(s))out=vids.filter(v=>v.id==='haXJFnDqkG0');
}
  return (out.length?out:vids.slice(0,2)).slice(0,2)}
function v25InjectStandaloneVideos(){const st=v22LibraryState;if(!st||st.cat==='Carrelage')return;const detail=document.querySelector('#v22Standalone .v22StandaloneDetail');if(!detail||detail.querySelector('.v25Related'))return;const steps=v22Steps(st.cat),name=steps[st.active||0]||'',videos=v25RelatedVideos(st.cat,name),ch=V25_CHANNELS[st.cat];const validate=detail.querySelector('button.full');const box=document.createElement('section');box.className='v25Related';box.innerHTML=`<div class="v24RelatedHead"><div><h4>🎥 Voir la démonstration</h4><small>Vidéos ${esc(ch?.name||'YouTube')} liées à cette étape.</small></div><button class="v24AllVideos" onclick='v25OpenVideoLibrary(${JSON.stringify(st.cat)})'>Toutes les vidéos →</button></div><div class="v24RelatedGrid">${videos.map(v=>v25VideoCard(st.cat,v)).join('')}</div>`;if(validate)detail.insertBefore(box,validate);else detail.appendChild(box)}
try{const v25BaseStandalone=v22RenderStandalone;v22RenderStandalone=function(){v25BaseStandalone();requestAnimationFrame(v25InjectStandaloneVideos)}}catch(_){}

function v25InjectHubVideos(){const hub=document.querySelector('#v21TutorHub .v21TutorHub');if(!hub||hub.querySelector('.v25HubVideos'))return;const anchor=hub.querySelector('.v24HubVideos')||hub.querySelector('.v22LibraryGrid');if(!anchor)return;const sec=document.createElement('section');sec.className='v25HubVideos';sec.innerHTML=`<h3 class="v25HubTitle">🎬 Vidéos tutoriels par métier</h3>${Object.keys(V25_CHANNELS).map(cat=>{const ch=V25_CHANNELS[cat],vids=V25_VIDEOS[cat]||[];return `<div class="v25HubTrade"><div class="v25HubTradeHead"><div><b>${meta[cat]?.[2]||'🔧'} ${esc(cat)} — ${esc(ch.name)}</b><small>${esc(ch.sub)} · ${vids.length} vidéos classées dans Bricoach</small></div><button class="btn soft" onclick='v25OpenVideoLibrary(${JSON.stringify(cat)})'>Voir toutes →</button></div><div class="v24HubVideoStrip">${vids.slice(0,4).map(v=>v25VideoCard(cat,v)).join('')}</div></div>`}).join('')}`;anchor.insertAdjacentElement('afterend',sec)}
try{const v25BaseHub=v21OpenTutorialHub;v21OpenTutorialHub=function(){v25BaseHub();requestAnimationFrame(v25InjectHubVideos)}}catch(_){}

requestAnimationFrame(()=>{try{v21PatchNavigation?.()}catch(_){}});
